#!/usr/bin/env python3
"""Generate the split User-Defined Tools that let the softmask workflow run on usegalaxy.org.

WHY A GENERATOR AND NOT FOUR HAND-WRITTEN YAML FILES. The awk and Python helpers under `tools/`
have to be INLINED into each UDT, because a UDT has no `$__tool_directory__`. Copying them by hand
produces a second copy that drifts from the wrapper the moment either is edited, which is the exact
failure `scripts/xml_to_udt.py` exists to avoid. This reads them from `tools/` at build time, so
`tools/` stays the single source.

⛔ WHY THE PORT IS TWO TOOLS PER MASKER RATHER THAN ONE. Each classic wrapper pipes a masker binary
through `lc_classify.py`, so one job needs BOTH the masker's biocontainer and a Python interpreter.
A UDT gets exactly one container, and `quay.io/biocontainers/blast` has no `python3` -- measured, a
converted dustmasker died with exit 127, `python3: command not found`. A mulled image would fix it,
but its hash is not derivable from the versions, so somebody has to build and publish one first.
Splitting costs one extra workflow step per masker and needs no new image at all. This is the same
conclusion `xml_to_udt.py` reaches when it refuses these wrappers; this script implements it.

⚠ THE MASKER EMITS ITS UPPERCASED FASTA AS A SECOND OUTPUT, AND THAT IS NOT A CONVENIENCE.
`lc_classify` reads the sequence to classify each interval, so it must read the SAME bases the
masker saw -- same decompression, same uppercasing, same header parsing. Handing it the original
assembly instead would agree almost always and disagree silently wherever the two paths differ,
which is the class of bug that does not announce itself.

    python3 scripts/build_softmask_udts.py            # writes udt/*.gxtool.yml
    python3 scripts/build_softmask_udts.py --check    # non-zero if the committed copies are stale
"""
from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
UDT = ROOT / "udt"

#: ⚠ Galaxy interpolates `$(...)` ANYWHERE in `shell_command`, heredocs included. An inlined helper
#: containing `$(` would be silently rewritten, so refuse rather than ship a corrupted script.
FORBIDDEN = "$("

HEADER = """# ⛔ GENERATED by scripts/build_softmask_udts.py -- do not hand-edit.
# Edit the wrapper under tools/ (the awk/Python helpers are read from there) and regenerate.
#
# WHY THIS IS TWO TOOLS AND NOT ONE. The classic wrapper pipes a masker binary through
# lc_classify.py, so one job needs BOTH the masker's biocontainer and a Python interpreter. A UDT
# gets exactly one container, and quay.io/biocontainers/blast has no python3 (measured: exit 127,
# "python3: command not found"). A mulled image would fix it but its hash is not derivable, so
# somebody has to build and publish one. Splitting costs one extra workflow step and no new image.
#
# ⚠ THE MASKER EMITS ITS UPPERCASED FASTA AS A SECOND OUTPUT, ON PURPOSE. lc_classify reads the
# sequence to classify each interval, and it must read the SAME bases the masker saw -- same
# decompression, same uppercasing. Feeding it the original assembly instead would usually agree and
# would silently disagree wherever the two paths differ.
"""

#: ⛔ NOT `gzip -cdf`. GNU gzip passes unrecognised input through with --stdout; the gzip inside the
#: blast biocontainer does not -- it fails `gzip: invalid magic` on a plain FASTA. Test and branch.
#: ⚠ NOT wrapped in `$(...)`: that is Galaxy's templating delimiter, not a shell substitution.
DECOMPRESS = (
    "  { if gzip -t '$(inputs.input.path)' 2>/dev/null; "
    "then gzip -cd '$(inputs.input.path)'; else cat '$(inputs.input.path)'; fi; } \\\n"
    "    | awk '/^>/{print;next}{print toupper($0)}' > upper.fa &&"
)


def indent(body: str, pad: str = "  ") -> str:
    return "\n".join(pad + line for line in body.splitlines())


def read_helper(relpath: str) -> str:
    body = (ROOT / relpath).read_text(encoding="utf-8").rstrip("\n")
    if FORBIDDEN in body:
        sys.exit(f"REFUSING: {relpath} contains `{FORBIDDEN}`, which Galaxy would interpolate "
                 f"inside the heredoc, corrupting the inlined script.")
    return body


def masker(tool_id, name, container, desc, cmd, helper_path, helper_name) -> str:
    helper = read_helper(helper_path)
    return HEADER + f"""class: GalaxyUserTool
id: {tool_id}
version: "0.1.0"
name: {name}
description: {desc}
container: {container}
shell_command: |
  cat > {helper_name} <<'BRC_AWK'
{indent(helper)}
  BRC_AWK
  set -o pipefail
{DECOMPRESS}
{cmd}
inputs:
  - name: input
    type: data
    format: fasta,fasta.gz
    label: Assembly FASTA
    help: plain or gzipped
outputs:
  - name: intervals
    type: data
    format: bed
    from_work_dir: intervals.bed3
    label: masked intervals (BED3, unclassified)
  - name: upper_fasta
    type: data
    format: fasta
    from_work_dir: upper.fa
    label: uppercased FASTA (feed to lc_classify alongside the intervals)
help:
  format: markdown
  content: |
    Stage 1 of a two-step port. Emits BED3 intervals plus the uppercased FASTA they index into.
    Feed BOTH to `brc-lc-classify` to get the content-annotated BED6 the workflow expects.
"""


def build() -> dict[str, str]:
    out = {}
    out["dustmasker_bed3.gxtool.yml"] = masker(
        "brc-dustmasker-bed3", "dustmasker -> BED3 (BRC UDT)",
        "quay.io/biocontainers/blast:2.17.0--h66d330f_0",
        "NCBI symmetric-DUST low-complexity intervals, stage 1 of 2",
        "  dustmasker -in upper.fa -outfmt interval | awk -f interval2bed.awk > intervals.bed3",
        "tools/dustmasker/interval2bed.awk", "interval2bed.awk")

    out["windowmasker_bed3.gxtool.yml"] = masker(
        "brc-windowmasker-bed3", "windowmasker -> BED3 (BRC UDT)",
        "quay.io/biocontainers/blast:2.17.0--h66d330f_0",
        "NCBI WindowMasker genome-frequency repeats, stage 1 of 2",
        "  windowmasker -mk_counts -in upper.fa -out counts &&\n"
        "  windowmasker -ustat counts -in upper.fa -outfmt interval"
        " | awk -f interval2bed.awk > intervals.bed3",
        "tools/dustmasker/interval2bed.awk", "interval2bed.awk")

    out["tantan_bed3.gxtool.yml"] = masker(
        "brc-tantan-bed3", "tantan -> BED3 (BRC UDT)",
        "quay.io/biocontainers/tantan:51--h4ac6f70_0",
        "tantan gentle low-complexity intervals, stage 1 of 2",
        "  tantan upper.fa | awk -f lc2bed.awk > intervals.bed3",
        "tools/tantan/lc2bed.awk", "lc2bed.awk")

    out["fasta_uppercase.gxtool.yml"] = HEADER + """class: GalaxyUserTool
id: brc-fasta-uppercase
version: "0.1.0"
name: Uppercase a FASTA (BRC UDT)
description: Strip any existing soft-mask so the workflow's output is its OWN mask and nothing else
container: quay.io/biocontainers/python:3.12
shell_command: |
  set -o pipefail
  python3 <<'BRC_PY'
  import gzip

  # ⛔ HEADER LINES ARE NEVER TOUCHED, AND THIS IS THE WHOLE CORRECTNESS ARGUMENT FOR THE TOOL.
  # Sequence names are CASE-SENSITIVE identifiers. Uppercasing a header rewrites the name -- `chr1`
  # becomes `CHR1` -- and every downstream join by name then silently finds nothing. A one-line
  # `tr '[:lower:]' '[:upper:]'` over the whole file does exactly that.
  src = '$(inputs.input.path)'
  with open(src, 'rb') as fh:
      gzipped = fh.read(2) == b'\\x1f\\x8b'
  op = (lambda p: gzip.open(p, 'rt', encoding='utf-8', errors='replace')) if gzipped \\
      else (lambda p: open(p, 'rt', encoding='utf-8', errors='replace'))

  lower = total = seqs = 0
  with op(src) as fin, open('uppercased.fasta', 'w', encoding='utf-8') as out:
      for line in fin:
          if line.startswith('>'):
              seqs += 1
              out.write(line)          # verbatim -- see above
              continue
          s = line.rstrip('\\n')
          total += len(s)
          lower += sum(1 for c in s if 'a' <= c <= 'z')
          out.write(s.upper())
          out.write('\\n')

  if seqs == 0:
      raise SystemExit('no FASTA headers found -- is this a FASTA file?')
  if total == 0:
      raise SystemExit('FASTA contains headers but no sequence')

  frac = lower / total
  print(f'sequences: {seqs:,}')
  print(f'residues:  {total:,}')
  print(f'soft-masked residues removed: {lower:,} ({frac:.1%})')
  if lower == 0:
      print('NOTE: input carried no soft-masking; this was a no-op')
  elif frac > 0.10:
      print(f'NOTE: a substantial existing mask ({frac:.1%}) was discarded. That is intended here '
            f'-- the workflow re-masks from scratch -- and is data loss anywhere else.')
  BRC_PY
inputs:
  - name: input
    type: data
    format: fasta,fasta.gz
    label: Assembly FASTA
    help: plain or gzipped; soft-masked or not
outputs:
  - name: output
    type: data
    format: fasta
    from_work_dir: uppercased.fasta
    label: Uppercased FASTA
help:
  format: markdown
  content: |
    Rewrites every sequence line in uppercase and leaves header lines exactly as they were.

    ⛔ **Why the workflow needs this as a SEPARATE step even though each masker already uppercases
    internally.** The maskers uppercase their own working copy, so the BED tracks are computed on
    unmasked sequence and are correct either way. But `bedtools maskfasta -soft` was applied to the
    ORIGINAL assembly, which lowercases the union intervals *on top of whatever was already
    lowercase*. For an assembly that arrives soft-masked -- cs10 ships **46.8%** masked from NCBI,
    while the other assemblies here are 0.0-0.7% -- the published `softmasked_fasta` was then the
    union of this workflow's mask AND NCBI's, indistinguishably. Feeding the uppercased FASTA to
    `maskfasta` makes the output exactly the mask this workflow computed.

    **Reports the fraction it removed**, so a no-op and a discarded 47% mask are distinguishable in
    the job log rather than both looking like success.
"""

    out["samtools_faidx.gxtool.yml"] = HEADER + """class: GalaxyUserTool
id: brc-samtools-faidx
version: "0.1.0"
name: samtools faidx (BRC UDT)
description: Index a FASTA (.fai) and emit the chrom/length table bedtools wants as its genome file
container: quay.io/biocontainers/samtools:1.24--h9dcdb79_1
shell_command: |
  set -o pipefail
  cp '$(inputs.input.path)' seq.fa
  samtools faidx seq.fa
  cut -f1,2 seq.fa.fai > chrom.sizes
inputs:
  - name: input
    type: data
    format: fasta
    label: FASTA to index
    help: plain FASTA. samtools faidx accepts bgzip but NOT ordinary gzip.
outputs:
  - name: output
    type: data
    format: fai
    from_work_dir: seq.fa.fai
    label: FASTA index (.fai)
  - name: sizes
    type: data
    format: tabular
    from_work_dir: chrom.sizes
    label: chrom/length table (bedtools genome file)
help:
  format: markdown
  content: |
    `faidx` is a SUBCOMMAND of samtools, not a separate program, so this wraps the samtools
    biocontainer and calls it.

    **Why this UDT exists at all.** `samtools_faidx` is published in the ToolShed but is NOT
    installed on usegalaxy.org -- a scan of all 2,370 tools in the panel returns no faidx of any
    kind, while twenty other samtools subcommands are present. `workflows/softmask` and
    `workflows/inventory` both reference `tool_id: samtools_faidx`, so both fail at invocation with
    "required tools are not installed" on that step.

    ⚠ **The copy is not redundant.** `samtools faidx` writes `<input>.fai` beside its input, and the
    Galaxy input path is read-only and outside the job's work dir, so indexing in place fails.

    The second output saves a step: the classic workflow ran `Cut c1,c2` over the `.fai` to build
    the bedtools genome file, which is exactly `chrom.sizes` here.
"""

    lc = read_helper("tools/dustmasker/lc_classify.py")
    out["lc_classify.gxtool.yml"] = HEADER + f"""class: GalaxyUserTool
id: brc-lc-classify
version: "0.1.0"
name: lc_classify -> BED6 (BRC UDT)
description: Annotate masked intervals with repeat-unit signature and purity, stage 2 of 2
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > lc_classify.py <<'BRC_PY'
{indent(lc)}
  BRC_PY
  set -o pipefail
  python3 lc_classify.py '$(inputs.fasta.path)' '$(inputs.intervals.path)' \\
    | LC_ALL=C sort -k1,1 -k2,2n > annotated.bed6
inputs:
  - name: fasta
    type: data
    format: fasta
    label: Uppercased FASTA
    help: the `upper_fasta` output of the matching stage-1 masker, NOT the original assembly
  - name: intervals
    type: data
    format: bed
    label: BED3 intervals
    help: the `intervals` output of the matching stage-1 masker
outputs:
  - name: output
    type: data
    format: bed
    from_work_dir: annotated.bed6
    label: content-annotated BED6
help:
  format: markdown
  content: |
    Stage 2 of the two-step masker port, shared by dustmasker, windowmasker and tantan.

    Column 4 carries the repeat-unit signature (`polyA`, `(AT)n`, or `lc`), column 5 the purity
    x1000 driving UCSC grayscale, column 6 `.`. This is `tools/dustmasker/lc_classify.py` inlined
    verbatim, not a reimplementation.
"""
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if a committed file differs from what would be generated")
    args = ap.parse_args()

    UDT.mkdir(exist_ok=True)
    stale = []
    for fn, body in build().items():
        path = UDT / fn
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if args.check:
            if current != body:
                stale.append(fn)
            continue
        path.write_text(body, encoding="utf-8")
        print(f"  {'unchanged' if current == body else 'wrote':>9} udt/{fn}")
    if args.check:
        for fn in stale:
            print(f"  STALE udt/{fn}")
        if stale:
            print("  Regenerate with: python3 scripts/build_softmask_udts.py")
            return 1
        print("  all committed UDTs match their sources")
    return 0


if __name__ == "__main__":
    sys.exit(main())
