#!/usr/bin/env python3
"""Generate WF-C2's User-Defined Tools by inlining the wrappers' own helper scripts.

    python3 scripts/build_projection_udts.py            # write udt/
    python3 scripts/build_projection_udts.py --check    # fail if a committed copy is stale

⛔ FIVE OF WF-C2's TWENTY-ONE STEPS NAME TOOLS usegalaxy.org DOES NOT HAVE, so the classic
workflow imports there and cannot be invoked at all: collection_self_pairs (already ported for
WF-A as `brc-self-pairs`), collection_anchor_grid, phase_c2_triage, toga2 and phase_c4_merge.
This generator emits the three that are portable.

⛔ toga2 IS NOT ONE OF THEM, AND NOT FOR WANT OF TRYING. A User-Defined Tool is a container plus a
command, so it can only wrap an image a Galaxy can PULL. tools/toga2/macros.xml records that
upstream ships only an apptainer/Singularity def -- no published Docker image, no bioconda package,
no biocontainer -- and that this project builds its own SIF onto shared storage at
/data/containers/toga2-2.0.8.sif. A local .sif path is not something usegalaxy.org can resolve.
Until an upstream image exists the TOGA2/CESAR2 rescue cannot run there by any means, which is why
workflows/align_chain_project/project_annotations_udt.gxwf.yml is the Liftoff-only pass.

⚠ THE PYTHON IS INLINED VERBATIM FROM tools/, NOT REWRITTEN. The XML wrappers read their scripts
from $__tool_directory__, which a UDT has no equivalent of, so the script travels in the command
itself -- and it travels UNCHANGED, so the two editions cannot drift into computing different
things. The one interface difference is collection_anchor_grid's: element identifiers arrive as
FILES rather than as a Cheetah-interpolated list, because a job container is handed paths and never
sees the identifiers of the collection they came from.
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
UDT = ROOT / "udt"

#: ⚠ Galaxy interpolates this sequence ANYWHERE in a shell_command, heredocs included, so a helper
#: carrying one -- even inside a comment or a docstring -- is rewritten on its way into the tool.
FORBIDDEN = "$("


def helper(relpath: str) -> str:
    """The wrapper's own script, indented into the heredoc, refused if it can be interpolated."""
    body = (ROOT / relpath).read_text(encoding="utf-8").rstrip("\n")
    if FORBIDDEN in body:
        sys.exit(f"REFUSING: {relpath} contains `{FORBIDDEN}`, which Galaxy would interpolate "
                 f"inside the heredoc, corrupting the inlined script.")
    return "\n".join(("  " + line).rstrip() for line in body.split("\n"))


ANCHOR_GRID = """\
# ⛔ GENERATED by scripts/build_projection_udts.py -- do not hand-edit.
# The Python below is inlined VERBATIM from tools/collection_anchor_grid/anchor_grid.py; edit it
# there and regenerate. Only the argument shape differs from the classic tool: the element
# identifiers arrive as FILES (from the IUC collection_element_identifiers tool) rather than as a
# Cheetah-interpolated list, because a job container receives paths and never sees a collection's
# identifiers.
class: GalaxyUserTool
id: brc-anchor-grid
version: "0.1.0"
name: anchor x strain chain grid (BRC UDT)
description: The keep list, relabel map and sort order that bridge WF-C's chains to WF-C2's grid
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > anchor_grid.py <<'BRC_PY'
{script}
  BRC_PY
  python3 anchor_grid.py --anchors-file '$(inputs.anchors.path)' \\
      --strains-file '$(inputs.strains.path)' \\
      --keep keep.txt --relabel relabel.tabular --order order.txt
inputs:
  - name: anchors
    type: data
    format: txt,tabular
    label: Anchor element identifiers
    help: >-
      One anchor name per line, in collection order. Produce it with the IUC
      `collection_element_identifiers` tool over the anchor collection -- a job container is handed
      paths and never sees the identifiers of the collection they came from.
  - name: strains
    type: data
    format: txt,tabular
    label: Strain (query) element identifiers
    help: >-
      One strain name per line, in collection order: the FULL panel. Every anchor must also appear
      here, because WF-C only produced chains for panel members; the tool refuses otherwise.
outputs:
  - name: keep
    type: data
    format: txt
    from_work_dir: keep.txt
    label: chain ids to keep
  - name: relabel
    type: data
    format: tabular
    from_work_dir: relabel.tabular
    label: chain relabel map
  - name: order
    type: data
    format: txt
    from_work_dir: order.txt
    label: grid order
help:
  format: markdown
  content: |
    WF-C emits one cleaned chain per ordered strain pair, keyed `{target}.{query}`. WF-C2's
    projection grid is anchors x strains with the anchor self-cells dropped, keyed
    `{anchor}_{query}`. TOGA2's `--chain_file` is the reference-to-query chain and its reference is
    the anchor, so the chain for cell `{anchor}_{query}` is the one whose TARGET is the anchor.

    Bridging the two needs three files, and this emits all three from nothing but the two
    collections' element identifiers:

    - `keep` -> `__FILTER_FROM_FILE__` (remove_if_absent), selecting the anchor-target chains
    - `relabel` -> `__RELABEL_FROM_FILE__` in **tabular** mode, renaming `A.B` to `A_B`
    - `order` -> `__SORTLIST__` with `sort_type: file`

    ⛔ **The third one is not optional.** Galaxy pairs collections in a map-over by POSITION, not
    by element identifier. The other grids come out of `__CROSS_PRODUCT_FLAT__` and are in
    anchor-collection order, while a chain collection filtered out of WF-C keeps WF-C's own
    alphabetical order. Without re-sorting, every cell is handed another cell's chain, TOGA2
    reports "Processed 0 chains" and exits -- and because the identifiers are all correct, nothing
    looks wrong.

    **Why a UDT.** `collection_anchor_grid` is not installed on usegalaxy.org, so WF-C2 cannot be
    invoked there. This is the same tool with the identifiers passed as files.
"""

TRIAGE = """\
# ⛔ GENERATED by scripts/build_projection_udts.py -- do not hand-edit.
# The Python below is inlined VERBATIM from tools/phase_c2_triage/phase_c2_triage.py; edit it there
# and regenerate. The XML wrapper reads the same file from $__tool_directory__, which a UDT has no
# equivalent of -- a User-Defined Tool ships nothing but its container -- so the script travels in
# the command itself.
class: GalaxyUserTool
id: brc-phase-c2-triage
version: "0.1.0"
name: Phase C.2 triage of Liftoff projections (BRC UDT)
description: Split a Liftoff projection into the genes that stand and the genes that need CESAR2
container: quay.io/biocontainers/pyfaidx:0.9.0.4--pyhdfd78af_0
shell_command: |
  cat > phase_c2_triage.py <<'BRC_PY'
{script}
  BRC_PY
  ln -s '$(inputs.query_fasta.path)' query.fasta &&
  mkdir -p outdir &&
  python3 phase_c2_triage.py \\
      --liftoff-gff '$(inputs.liftoff_gff.path)' \\
      --query-fasta query.fasta \\
      --reference-bed '$(inputs.reference_bed.path)' \\
      --query-name '$(inputs.query_name)' \\
      --output-dir outdir \\
      --core-identity-min $(inputs.core_identity_min) \\
      --core-coverage-min $(inputs.core_coverage_min) \\
      --family-identity-min $(inputs.family_identity_min) \\
      --subtelomere-bp $(inputs.subtelomere_bp) \\
      $(inputs.family_list ? "--family-list '" + inputs.family_list.path + "'" : "") \\
      --log-level INFO
inputs:
  - name: liftoff_gff
    type: data
    format: gff3,gff
    label: Liftoff GFF3
    help: >-
      Projected gene annotation from Liftoff. Genes must carry the attributes the triage rules
      read: sequence_ID, coverage, extra_copy_number, valid_ORFs, partial_mapping.
  - name: query_fasta
    type: data
    format: fasta
    label: Query genome FASTA
    help: >-
      The query assembly the GFF coordinates refer to; seqids must match the GFF chrom column.
      ⚠ STAGED UNDER A REAL NAME. Galaxy hands a job an extensionless `.dat`, and pyfaidx writes
      and reads its index beside the file it was given, so the tool symlinks it to `query.fasta`
      first -- exactly as the XML wrapper does.
  - name: reference_bed
    type: data
    format: bed
    label: Reference BED12
    help: >-
      Reference gene models in BED. Column 4 must carry the (normalized) gene ids, or a flagged
      gene cannot be written into needs_cesar2.bed. WF-A's anchor_prep produces this.
  - name: query_name
    type: text
    value: query
    label: Name to record for this query genome
    help: Recorded in summary.json. Letters, digits, underscore, hyphen and dot only.
    validators:
      # ⚠ THE FIELD IS `expression`, NOT `regex`. The XML spelling is
      # `<validator type="regex">PATTERN</validator>`, and carrying that name over produced four
      # pydantic errors at once -- RegexParameterValidatorModel.expression missing AND `regex`
      # rejected as an extra field. Caught by galaxy-tool-util, which is the whole reason
      # check_udt_definitions.py calls the server's own model when it is installed.
      - type: regex
        message: Letters, digits, underscore, hyphen, dot only
        expression: "[A-Za-z0-9_.-]+"
  - name: family_list
    type: data
    format: tabular
    optional: true
    label: Gene family list (optional)
    help: >-
      Optional TSV of (gene_id, family) for known variant-gene families -- SICAvar, PIR and the
      like. Supplied, rule R8 forces those genes to CESAR2 fallback and relaxes the identity
      threshold for them.
  - name: core_identity_min
    type: float
    value: 0.95
    min: 0.0
    max: 1.0
    label: Core gene minimum identity
    help: Rule R2 threshold for genes NOT on the family list.
  - name: core_coverage_min
    type: float
    value: 0.9
    min: 0.0
    max: 1.0
    label: Minimum reference CDS coverage
    help: Rule R3 threshold.
  - name: family_identity_min
    type: float
    value: 0.85
    min: 0.0
    max: 1.0
    label: Family gene minimum identity
    help: Rule R2 threshold for genes ON the family list. Ignored when no family list is given.
  - name: subtelomere_bp
    type: integer
    value: 100000
    min: 0
    label: Subtelomere flank (bp)
    help: Rule R7 flags genes within this distance of a chromosome end.
outputs:
  - name: triage_tsv
    type: data
    format: tabular
    from_work_dir: outdir/triage.tsv
    label: triage.tsv
  - name: needs_cesar2_bed
    type: data
    format: bed
    from_work_dir: outdir/needs_cesar2.bed
    label: needs_cesar2.bed
  - name: liftoff_clean_gff3
    type: data
    format: gff3
    from_work_dir: outdir/liftoff_clean.gff3
    label: liftoff_clean.gff3
  - name: summary_json
    type: data
    format: json
    from_work_dir: outdir/summary.json
    label: summary.json
help:
  format: markdown
  content: |
    Phase C.2 of the projection pipeline. Liftoff projects an anchor's genes onto a query; this
    decides which of those projections can be trusted as they are and which have to be re-projected
    by TOGA2/CESAR2 through the chain alignment.

    **Outputs.** `liftoff_clean.gff3` is the accepted subset -- the only one Phase C.4 needs for a
    Liftoff-only pass. `needs_cesar2.bed` is the reference-coordinate BED of the flagged genes,
    `triage.tsv` is the per-gene rule trace, and `summary.json` carries the counts.

    **Why a UDT.** `phase_c2_triage` is not installed on usegalaxy.org, so WF-C2 cannot be invoked
    there at all. This is the same script, in the pyfaidx biocontainer, with the file it needs
    staged under a real name.

    ⚠ A fallback rate above 50% is reported as a warning, not an error -- it usually means the
    thresholds are wrong for the clade rather than that the projection failed.
"""

C4_MERGE = """\
# ⛔ GENERATED by scripts/build_projection_udts.py -- do not hand-edit.
# The Python below is inlined VERBATIM from tools/phase_c4_merge/phase_c4_merge.py; edit it there
# and regenerate.
class: GalaxyUserTool
id: brc-phase-c4-merge
version: "0.1.0"
name: Phase C.4 merge into one annotation (BRC UDT)
description: Merge the Liftoff-clean projection with TOGA2/CESAR2 rescue into one annotation per query
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > phase_c4_merge.py <<'BRC_PY'
{script}
  BRC_PY
  mkdir -p triage_dir toga_dir out_dir &&
  ln -s '$(inputs.liftoff_clean.path)' triage_dir/liftoff_clean.gff3 &&
  $(inputs.loss_summary ? "ln -s '" + inputs.loss_summary.path + "' toga_dir/loss_summary.tsv &&" : "")
  $(inputs.orthology ? "ln -s '" + inputs.orthology.path + "' toga_dir/orthology_classification.tsv &&" : "")
  $(inputs.query_annotation ? "ln -s '" + inputs.query_annotation.path + "' toga_dir/query_annotation.bed &&" : "")
  $(inputs.query_genes ? "ln -s '" + inputs.query_genes.path + "' toga_dir/query_genes.bed &&" : "")
  if { [ -e toga_dir/loss_summary.tsv ] && [ ! -e toga_dir/orthology_classification.tsv ]; } ||
     { [ ! -e toga_dir/loss_summary.tsv ] && [ -e toga_dir/orthology_classification.tsv ]; }; then
    echo "⛔ brc-phase-c4-merge: TOGA2 rescue needs BOTH loss_summary and orthology_classification." >&2
    echo "   Exactly one was supplied. With neither, this runs the Liftoff-only pass and every" >&2
    echo "   projected gene is tagged source=liftoff -- a legitimate and common mode. With one," >&2
    echo "   the merge would silently read an empty TOGA directory and produce that SAME output" >&2
    echo "   while looking like a rescue pass. REFUSING." >&2
    exit 1
  fi &&
  python3 phase_c4_merge.py \\
      --query '$(inputs.query)' \\
      --triage-dir triage_dir \\
      --toga-dir toga_dir \\
      --out-dir out_dir \\
      --ref-bed '$(inputs.ref_bed.path)' &&
  mv out_dir/*.annotation.gff3 annotation.gff3 &&
  mv out_dir/*.classification.tsv classification.tsv
inputs:
  - name: query
    type: text
    value: query
    label: Query strain name
    help: >-
      Names the files the script writes, and nothing else -- it is not written into them. Letters,
      digits, underscore, hyphen and dot only.
    validators:
      # ⚠ THE FIELD IS `expression`, NOT `regex`. The XML spelling is
      # `<validator type="regex">PATTERN</validator>`, and carrying that name over produced four
      # pydantic errors at once -- RegexParameterValidatorModel.expression missing AND `regex`
      # rejected as an extra field. Caught by galaxy-tool-util, which is the whole reason
      # check_udt_definitions.py calls the server's own model when it is installed.
      - type: regex
        message: Letters, digits, underscore, hyphen, dot only
        expression: "[A-Za-z0-9_.-]+"
  - name: liftoff_clean
    type: data
    format: gff3,gff
    label: Liftoff-clean GFF3
    help: >-
      The triage-accepted projection (liftoff_clean.gff3 from Phase C.2). Genes here are tagged
      source=liftoff, intactness=I.
  - name: ref_bed
    type: data
    format: bed
    label: Reference gene BED12
    help: >-
      Reference annotation in BED12; column 4 is the reference gene id. A gene present here and
      absent from both projections is reported as source=none, intactness=M.
  - name: loss_summary
    type: data
    format: tabular
    optional: true
    label: TOGA2 loss_summary.tsv (optional)
    help: >-
      Supply this AND orthology_classification to merge a TOGA2/CESAR2 rescue pass. Leave both
      empty for the Liftoff-only pass. Supplying exactly one is refused, because the merge would
      otherwise read an empty TOGA directory and produce the Liftoff-only answer while looking
      like a rescue.
  - name: orthology
    type: data
    format: tabular
    optional: true
    label: TOGA2 orthology_classification.tsv (optional)
    help: The other half of the pair. See loss_summary.
  - name: query_annotation
    type: data
    format: bed
    optional: true
    label: TOGA2 query_annotation.bed (optional)
    help: Transcript-level query coordinates. Optional even in a rescue pass.
  - name: query_genes
    type: data
    format: bed
    optional: true
    label: TOGA2 query_genes.bed (optional)
    help: Gene-level query coordinates; used to emit the CESAR2 GFF lines.
outputs:
  - name: annotation_gff3
    type: data
    format: gff3
    from_work_dir: annotation.gff3
    label: merged annotation
  - name: classification_tsv
    type: data
    format: tabular
    from_work_dir: classification.tsv
    label: per-gene classification
help:
  format: markdown
  content: |
    Phase C.4. One annotation per query genome, built from the Liftoff projection that survived
    triage plus -- optionally -- the TOGA2/CESAR2 rescue of the genes that did not.

    **Two modes, and the tool refuses the half-supplied third.** With no TOGA2 inputs this is the
    Liftoff-only pass 1: every projected gene is tagged `source=liftoff`, and a reference gene
    absent from the projection is reported `source=none, intactness=M`. With `loss_summary` AND
    `orthology` it merges the rescue and reports TOGA2's own intactness classes (I/PI/UL/PG/L/M/FI).

    ⛔ **A rescue pass on usegalaxy.org is not currently possible**, because TOGA2 itself has no
    published container -- see the WF-C2 workflow doc. This tool takes the inputs anyway, so the
    moment an image exists nothing here has to change.

    **Why a UDT.** `phase_c4_merge` is not installed on usegalaxy.org, so WF-C2 cannot be invoked
    there. Same script, same behaviour, in the stock python biocontainer.

    ⚠ The output filenames the script writes are keyed on the query name, so the command moves them
    to fixed names before Galaxy claims them.
"""



def build() -> dict[str, str]:
    """filename -> file body. `.replace`, NOT `.format`: the help text is full of literal
    `{anchor}_{query}` braces -- they are the naming convention these tools exist to bridge -- and
    str.format reads every one of them as a field."""
    return {
        "anchor_grid.gxtool.yml":
            ANCHOR_GRID.replace("{script}", helper("tools/collection_anchor_grid/anchor_grid.py")),
        "phase_c2_triage.gxtool.yml":
            TRIAGE.replace("{script}", helper("tools/phase_c2_triage/phase_c2_triage.py")),
        "phase_c4_merge.gxtool.yml":
            C4_MERGE.replace("{script}", helper("tools/phase_c4_merge/phase_c4_merge.py")),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare against udt/ and exit non-zero if any committed copy is stale")
    args = ap.parse_args()

    stale = []
    for filename, body in build().items():
        path = UDT / filename
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != body:
                stale.append(filename)
            continue
        path.write_text(body, encoding="utf-8")
        print(f"  {'unchanged' if current == body else 'wrote':>9} udt/{filename}")

    if args.check:
        for filename in stale:
            print(f"  STALE udt/{filename}")
        if stale:
            print("  Regenerate with: python3 scripts/build_projection_udts.py")
            return 1
        print(f"  all committed projection UDTs match their helpers ({len(build())} generated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
