#!/usr/bin/env python3
"""Generate the split User-Defined Tools that let the softmask workflow run on usegalaxy.org.

WHY A GENERATOR AND NOT HAND-WRITTEN YAML FILES. The awk and Python helpers under `tools/` have to
be INLINED into each UDT, because a UDT has no `$__tool_directory__`. Copying them by hand produces
a second copy that drifts from the wrapper the moment either is edited.

⚠ THAT IS TRUE OF THE HELPERS ONLY, AND IT IS WORTH BEING PRECISE ABOUT. The command lines, the
container tags and the input/output declarations are hardcoded in `build()` -- a second copy of
`tools/<tool>/<tool>.xml` by any honest reading. `--check` compares generated YAML against `udt/`,
so on its own it CANNOT see a change made to the XML. `assert_sources_aligned()` closes the biggest
part of that hole by asserting the command fragments this file hardcodes still appear in the XML it
claims to mirror, and that the duplicated helper copies have not diverged from one another. It is a
tripwire, not a derivation: only a real converter could remove the duplication, and these wrappers
refuse conversion for reasons that are correct (see the notes below).

⛔ WHY THE PORT IS TWO TOOLS PER MASKER RATHER THAN ONE. Each classic wrapper pipes a masker binary
through `lc_classify.py`, so one job needs BOTH the masker's biocontainer and a Python interpreter.
A UDT gets exactly one container, and `quay.io/biocontainers/blast` has no `python3` -- measured, a
converted dustmasker died with exit 127, `python3: command not found`. A mulled image would fix it, and
⚠ its name IS derivable -- `v2_image_name` returns mulled-v2-21537411c4771e4e702855210543bee025cca4e0
for blast + python in one call -- but no such image is PUBLISHED (checked against the depot's 3,472
mulled-v2 images), so somebody has to register one first.
Splitting costs one extra workflow step per masker and needs no new image at all.

⚠ THE MASKER EMITS ITS UPPERCASED FASTA AS A SECOND OUTPUT, AND THAT IS NOT A CONVENIENCE.
`lc_classify` reads the sequence to classify each interval, so it must read the SAME bases the
masker saw -- same decompression, same uppercasing, same header parsing. Handing it the original
assembly instead would agree almost always and disagree silently wherever the two paths differ,
which is the class of bug that does not announce itself.

    python3 scripts/build_softmask_udts.py            # writes udt/*.gxtool.yml
    python3 scripts/build_softmask_udts.py --check    # non-zero if the committed copies are stale
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent.parent
UDT = ROOT / "udt"

#: ⚠ Galaxy interpolates `$(...)` ANYWHERE in `shell_command`, heredocs included. An inlined helper
#: containing `$(` would be silently rewritten, so refuse rather than ship a corrupted script.
FORBIDDEN = "$("

HEADER = """# ⛔ GENERATED by scripts/build_softmask_udts.py -- do not hand-edit.
# Edit the wrapper under tools/ (the awk/Python helpers are read from there) and regenerate.
"""

#: Appended to the UDTs that exist as a PAIR (masker -> lc_classify) rather than as one tool.
#:
#: ⚠ IT IS APPENDED, NOT BUILT IN, BECAUSE IT IS NOT TRUE OF EVERY UDT HERE. It was part of the
#: universal header, so `samtools_faidx`, `fasta_uppercase` and the two masking-table tools each
#: shipped an explanation of a split they are not part of -- a reader checking the claim against
#: those files finds one pipe and no second stage.
FASTAN_NOTE = """#
# WHY THE FASTAN PORT IS THREE TOOLS. The classic wrapper needs binaries from TWO conda packages --
# fastan 0.8 builds and scans, fastga 1.5.20260729 makes the GDB and reads the .1ano -- and a UDT
# gets one container. Each stage therefore runs in the image that owns its binary.
#
# ⚠ THE MULLED NAME IS DERIVABLE HERE TOO: v2_image_name gives
# mulled-v2-63f8cfa6f4ca8e7d661b40ea4b0ff4f493a7ec57 for fastan 0.8 + fastga 1.5.20260729. It is
# not published either -- so this split, like the masker/classify one, is a workaround for a
# publication gap rather than for an unknowable hash.
"""

SPLIT_NOTE = """#
# WHY THIS IS TWO TOOLS AND NOT ONE. The classic wrapper pipes a masker binary through
# lc_classify.py, so one job needs BOTH the masker's biocontainer and a Python interpreter. A UDT
# gets exactly one container, and quay.io/biocontainers/blast has no python3 (measured: exit 127,
# "python3: command not found").
#
# ⚠ A MULLED IMAGE WOULD FIX IT AND ITS NAME IS DERIVABLE -- an earlier version of this note said
# the opposite. galaxy.tool_util.deps.mulled.util.v2_image_name gives
# mulled-v2-21537411c4771e4e702855210543bee025cca4e0 for blast 2.17.0 + python 3.12 in one call.
# What is missing is a PUBLISHED image: neither that one nor the tantan equivalent appears among
# the 3,472 mulled-v2 images in the Galaxy depot. So the split is a workaround for a publication
# gap, not for an unknowable hash, and `planemo container_register` is the way to close it.
# Splitting costs one extra workflow step and needs no new image today.
#
# ⚠ THE MASKER EMITS ITS UPPERCASED FASTA AS A SECOND OUTPUT, ON PURPOSE. lc_classify reads the
# sequence to classify each interval, and it must read the SAME bases the masker saw -- same
# decompression, same uppercasing. Feeding it the original assembly instead would usually agree and
# would silently disagree wherever the two paths differ.
"""

#: ⛔ NOT `gzip -cdf`. GNU gzip passes unrecognised input through with --stdout; the gzip inside the
#: blast biocontainer does not -- it fails `gzip: invalid magic` on a plain FASTA. Test and branch.
#: ⚠ NOT wrapped in `$(...)`: that is Galaxy's templating delimiter, not a shell substitution.
DECOMPRESS = (
    "  { if gzip -t '$(inputs.input.path)' 2>/dev/null; "
    "then gzip -cd '$(inputs.input.path)'; else cat '$(inputs.input.path)'; fi; } \\\n"
    "    | awk '/^>/{print;next}{print toupper($0)}' > upper.fa &&"
)


def indent(body: str, pad: str = "  ") -> str:
    return "\n".join(pad + line for line in body.splitlines())


def read_helper(relpath: str) -> str:
    body = (ROOT / relpath).read_text(encoding="utf-8").rstrip("\n")
    if FORBIDDEN in body:
        sys.exit(f"REFUSING: {relpath} contains `{FORBIDDEN}`, which Galaxy would interpolate "
                 f"inside the heredoc, corrupting the inlined script.")
    return body


def masker(tool_id, name, container, desc, cmd, helper_path, helper_name) -> str:
    helper = read_helper(helper_path)
    return HEADER + SPLIT_NOTE + f"""class: GalaxyUserTool
id: {tool_id}
version: "0.1.0"
name: {name}
description: {desc}
container: {container}
shell_command: |
  cat > {helper_name} <<'BRC_AWK'
{indent(helper)}
  BRC_AWK
  set -o pipefail
{DECOMPRESS}
{cmd}
inputs:
  - name: input
    type: data
    format: fasta,fasta.gz
    label: Assembly FASTA
    help: plain or gzipped
outputs:
  - name: intervals
    type: data
    format: bed
    from_work_dir: intervals.bed3
    label: masked intervals (BED3, unclassified)
  - name: upper_fasta
    type: data
    format: fasta
    from_work_dir: upper.fa
    label: uppercased FASTA (feed to lc_classify alongside the intervals)
help:
  format: markdown
  content: |
    Stage 1 of a two-step port. Emits BED3 intervals plus the uppercased FASTA they index into.
    Feed BOTH to `brc-lc-classify` to get the content-annotated BED6 the workflow expects.
"""


#: The masker columns, in the one order both the header and masking_table.py must use.
MASKER_COLUMNS = ("dustmasker", "windowmasker", "tantan", "fastan", "union")

#: UDTs that live in udt/ but are deliberately NOT generated, with the reason.
#: ⚠ Anything here is exempt from the staleness check, so the list should stay short.
HAND_WRITTEN_UDTS = frozenset({
    # The anchor half of WF-A. Hand-written because its awk is not a helper under tools/ that this
    # generator inlines -- it is a reimplementation of tools/anchor_prep/build_anchor_inputs.py,
    # verified byte-identical against it rather than generated from it. Left undeclared it is an
    # ORPHAN to --check, which turns udt-drift red on every PR touching udt/**.
    "anchor_prep.gxtool.yml",
    # A diagnostic, not part of the workflow: it dumps the job container's environment so the
    # platform claims in these tools' help text rest on a measurement. Nothing generates it because
    # nothing in tools/ corresponds to it.
    "env_probe.gxtool.yml",
    # A GPU node diagnostic, not part of any workflow: it reports the driver, device nodes and host
    # a GPU job lands on, from inside KegAlign's own image. Written after a KegAlign job failed with
    # "No GPU device found!" and its immediate rerun succeeded -- a difference the job's own stderr
    # cannot explain and, without admin-visible job metrics, nothing else here can either.
    "gpu_probe.gxtool.yml",
    # Asks what a `data_collection` input renders to inside a UDT job, and whether element
    # identifiers survive into it. That answer gates the sourmash, masking_table, multiz_fold and
    # phase_e_consensus ports, all of which iterate a collection reading identifiers.
    "collection_probe.gxtool.yml",
})

#: Command fragments this file hardcodes, and the wrapper each is copied from.
#:
#: ⛔ THESE ARE MATCHED AGAINST THE <command> ELEMENT ONLY, NOT THE WHOLE FILE. An earlier version
#: searched the raw XML text, and prose satisfied the anchors: `tantan ` matches
#: `<description>tantan gentle low-complexity...`, `FasTAN` and `ANOtoBED` appear in fastan.xml's
#: comment and help. An adversarial pass gutted tantan's entire <command>, left `lc2bed.awk` in a
#: `## FIXME` comment, and the tripwire passed.
XML_ANCHORS = {
    "tools/dustmasker/dustmasker.xml": ["dustmasker -in", "-outfmt interval", "interval2bed.awk",
                                        "lc_classify.py", "toupper"],
    "tools/windowmasker/windowmasker.xml": ["windowmasker -mk_counts", "windowmasker -ustat",
                                            "-outfmt interval", "interval2bed.awk",
                                            "lc_classify.py", "toupper"],
    "tools/tantan/tantan.xml": ["tantan in.fa", "lc2bed.awk", "lc_classify.py", "toupper"],
    "tools/fastan/fastan.xml": ["FAtoGDB", "FasTAN", "ANOtoBED", "ano2bed6.awk", "toupper"],
    "tools/masking_table/masking_table.xml": ["masking_table.py", "--dustmasker", "--union"],
}

#: ⛔ VERSIONS ARE ANCHORED SEPARATELY, BECAUSE THEY ARE THE DRIFT THAT ACTUALLY HAPPENS. No command
#: fragment contains a version, so a `<requirement>` bump sails past the anchors above while the
#: container pinned in build() stays put -- and the two then run different software. This repo's own
#: recent history is requirement edits to these very files.
XML_REQUIREMENTS = {
    "tools/dustmasker/dustmasker.xml": {"blast": "2.17.0"},
    "tools/windowmasker/windowmasker.xml": {"blast": "2.17.0"},
    "tools/tantan/tantan.xml": {"tantan": "51"},
    # ⚠ BOTH packages, because both are pinned in build(). `fastga` was left out, so the bump from
    # 1.5 to 1.5.20260729 (commit a45e0a7, on this branch) sailed past assert_sources_aligned while
    # `fastan_gdb` and `fastan_bed` kept their container -- the exact drift the header above claims
    # this block covers, performed by this repo, on this file. It is not cosmetic: released fastga
    # 1.5's ANOtoBED cannot open a .1ano written by fastan 0.8, which is why the bump happened.
    "tools/fastan/fastan.xml": {"fastan": "0.8", "fastga": "1.5.20260729"},
    "tools/masking_table/masking_table.xml": {"python": "3.12"},
}

#: Helper files duplicated across wrapper directories. They are byte-identical today; a fix applied
#: to one copy would otherwise never reach the UDT, which reads only the first.
#: ⚠ Hand-written, so it is "every duplicate someone remembered". `assert_no_new_duplicates()`
#: closes that by searching for duplicate content rather than trusting this list.
DUPLICATED_HELPERS = (
    ("tools/dustmasker/lc_classify.py", "tools/tantan/lc_classify.py",
     "tools/windowmasker/lc_classify.py"),
    ("tools/dustmasker/interval2bed.awk", "tools/windowmasker/interval2bed.awk"),
)

#: Content-duplicate files that are NOT inlined helpers, so divergence between them is harmless.
DUPLICATE_ALLOWLIST = {("tools/sourmash_compare/macros.xml", "tools/sourmash_sketch/macros.xml")}


def command_text(xml_path: pathlib.Path) -> str:
    """The <command> element's EXECUTABLE text: comments and Cheetah directives stripped.

    ⛔ COMMENTS INSIDE <command> COUNT AS PROSE, TOO. Scoping the anchors to <command> stopped
    `<description>tantan gentle...` from satisfying the `tantan ` anchor, but an adversarial pass
    then gutted the command body and left the anchor strings in a `## FIXME` comment -- and the
    tripwire passed again. `##` is Cheetah's comment marker, so anything after it never reaches a
    shell and must not be able to satisfy an anchor.
    """
    root = ET.parse(xml_path).getroot()
    el = root.find("command")
    if el is None or not el.text:
        sys.exit(f"REFUSING: {xml_path} has no <command> element to anchor against.")
    lines = []
    for raw in el.text.splitlines():
        line = raw.split("##", 1)[0]
        if line.strip().startswith("#"):       # a Cheetah directive, not a command
            continue
        lines.append(line)
    return "\n".join(lines)


def assert_sources_aligned() -> None:
    """Refuse to generate if `tools/` has moved out from under the hardcoded half of this file."""
    for xml, anchors in XML_ANCHORS.items():
        path = ROOT / xml
        if not path.is_file():
            sys.exit(f"REFUSING: {xml} is missing; this generator mirrors it.")
        cmd = command_text(path)
        for a in anchors:
            if a not in cmd:
                sys.exit(f"REFUSING: the <command> of {xml} no longer contains {a!r}, which this "
                         f"generator hardcodes.\n  The wrapper changed and the generated UDT would "
                         f"silently keep running the old command. Reconcile build() with the XML, "
                         f"then regenerate.")
    for xml, reqs in XML_REQUIREMENTS.items():
        root = ET.parse(ROOT / xml).getroot()
        got = {r.text.strip(): r.get("version") for r in root.iter("requirement")
               if r.get("type") == "package" and r.text}
        for pkg, ver in reqs.items():
            if got.get(pkg) != ver:
                sys.exit(f"REFUSING: {xml} requires {pkg} {got.get(pkg)!r}, but this generator "
                         f"pins a container built for {ver!r}.\n  A requirement bump without a "
                         f"matching container change makes the classic wrapper and the UDT run "
                         f"different software. Update CONTAINERS and this table together.")
    for group in DUPLICATED_HELPERS:
        digests = {}
        for rel in group:
            path = ROOT / rel
            if not path.is_file():
                sys.exit(f"REFUSING: {rel} is missing.")
            digests[rel] = hashlib.sha256(path.read_bytes()).hexdigest()
        if len(set(digests.values())) > 1:
            listing = "\n    ".join(f"{d[:12]}  {r}" for r, d in digests.items())
            sys.exit(f"REFUSING: duplicated helper copies have DIVERGED:\n    {listing}\n"
                     f"  Only the first is inlined, so the others' UDTs would ship stale logic. "
                     f"Reconcile them first.")
    assert_no_new_duplicates()
    assert_column_order()


def assert_no_new_duplicates() -> None:
    """Find duplicate helper content DUPLICATED_HELPERS does not know about.

    ⚠ A fourth copy of lc_classify.py landing in tools/longdust/ or tools/sdust/ -- both sibling
    low-complexity maskers here -- would diverge silently, because only the first copy is ever
    inlined and the hand-written list would not mention it.
    """
    seen: dict[str, list[str]] = {}
    known = {rel for group in DUPLICATED_HELPERS for rel in group}
    for path in sorted((ROOT / "tools").rglob("*")):
        if not path.is_file() or "test-data" in path.parts:
            continue
        if path.suffix not in (".py", ".awk", ".sh"):
            continue
        seen.setdefault(hashlib.sha256(path.read_bytes()).hexdigest(), []).append(
            str(path.relative_to(ROOT)))
    for digest, files in seen.items():
        if len(files) < 2:
            continue
        if set(files) <= known or tuple(sorted(files)) in DUPLICATE_ALLOWLIST:
            continue
        sys.exit(f"REFUSING: {len(files)} files share content {digest[:12]} and are not in "
                 f"DUPLICATED_HELPERS:\n    " + "\n    ".join(files) + "\n"
                 "  Only one copy is inlined into a UDT, so the others could diverge unnoticed. "
                 "Add them to DUPLICATED_HELPERS (or to DUPLICATE_ALLOWLIST if they are not "
                 "inlined anywhere).")


def assert_column_order() -> None:
    """The header's column order must match the order masking_table.py actually emits.

    ⛔ THIS IS THE ONE THE HELP TEXT ADMITTED WAS UNGUARDED, AND IT IS THE WORST OF THEM. Reordering
    masking_table.py's `maskers` list -- putting `union` first, say -- regenerates BOTH files
    consistently: `--check` passes, the anchors pass, and every percentage in the published MultiQC
    table is labelled with the wrong masker. Demonstrated by an adversarial pass; `--check` even
    TELLS you to regenerate, and regenerating is the step that hides the damage.
    """
    src = (ROOT / "tools/masking_table/masking_table.py").read_text(encoding="utf-8")
    block = re.search(r"maskers\s*=\s*\[(.*?)\]", src, re.DOTALL)
    if not block:
        sys.exit("REFUSING: cannot find the `maskers` list in masking_table.py to check its order.")
    order = re.findall(r'\("(\w+)"', block.group(1))
    if order != list(MASKER_COLUMNS):
        sys.exit(f"REFUSING: masking_table.py emits columns in the order {order}, but "
                 f"brc-masking-header prints {list(MASKER_COLUMNS)}.\n  Every percentage in the "
                 f"published table would be labelled with the wrong masker, and nothing else would "
                 f"fail. Reconcile the two.")


def build() -> dict[str, str]:
    out = {}
    out["dustmasker_bed3.gxtool.yml"] = masker(
        "brc-dustmasker-bed3", "dustmasker -> BED3 (BRC UDT)",
        "quay.io/biocontainers/blast:2.17.0--h66d330f_0",
        "NCBI symmetric-DUST low-complexity intervals, stage 1 of 2",
        "  dustmasker -in upper.fa -outfmt interval | awk -f interval2bed.awk > intervals.bed3",
        "tools/dustmasker/interval2bed.awk", "interval2bed.awk")

    out["windowmasker_bed3.gxtool.yml"] = masker(
        "brc-windowmasker-bed3", "windowmasker -> BED3 (BRC UDT)",
        "quay.io/biocontainers/blast:2.17.0--h66d330f_0",
        "NCBI WindowMasker genome-frequency repeats, stage 1 of 2",
        "  windowmasker -mk_counts -in upper.fa -out counts &&\n"
        "  windowmasker -ustat counts -in upper.fa -outfmt interval"
        " | awk -f interval2bed.awk > intervals.bed3",
        "tools/dustmasker/interval2bed.awk", "interval2bed.awk")

    out["tantan_bed3.gxtool.yml"] = masker(
        "brc-tantan-bed3", "tantan -> BED3 (BRC UDT)",
        # ⛔ THIS TAG WAS A GUESS AND IT DOES NOT EXIST. `51--h4ac6f70_0`: quay reports zero tags
        # for it and depot.galaxyproject.org 404s. The tool REGISTERS fine on usegalaxy.org --
        # creating a UDT does not resolve its image -- so it fails only at job start, with
        # `manifest unknown`, which means WF-B's UDT edition has never run end to end. The
        # udt-authoring skill names guessing the `--<hash>_<build>` suffix as the single most
        # common real UDT failure, and this is that failure. `51--h5ca1c30_1` is one of the two
        # builds that actually exist (quay: 1 tag, depot: HTTP 200); check_udt_definitions.py
        # --check-containers now asks, so a guess cannot ship again.
        "quay.io/biocontainers/tantan:51--h5ca1c30_1",
        "tantan gentle low-complexity intervals, stage 1 of 2",
        "  tantan upper.fa | awk -f lc2bed.awk > intervals.bed3",
        "tools/tantan/lc2bed.awk", "lc2bed.awk")

    out["fasta_uppercase.gxtool.yml"] = HEADER + """class: GalaxyUserTool
id: brc-fasta-uppercase
version: "0.1.0"
name: Uppercase a FASTA (BRC UDT)
description: Strip any existing soft-mask so the workflow's output is its OWN mask and nothing else
container: quay.io/biocontainers/python:3.12
shell_command: |
  set -o pipefail
  python3 <<'BRC_PY'
  import gzip

  # ⛔ HEADER LINES ARE NEVER TOUCHED, AND THIS IS THE WHOLE CORRECTNESS ARGUMENT FOR THE TOOL.
  # Sequence names are CASE-SENSITIVE identifiers. Uppercasing a header rewrites the name -- `chr1`
  # becomes `CHR1` -- and every downstream join by name then silently finds nothing. A one-line
  # `tr '[:lower:]' '[:upper:]'` over the whole file does exactly that.
  src = '$(inputs.input.path)'
  with open(src, 'rb') as fh:
      gzipped = fh.read(2) == b'\\x1f\\x8b'
  op = (lambda p: gzip.open(p, 'rt', encoding='utf-8', errors='replace')) if gzipped \\
      else (lambda p: open(p, 'rt', encoding='utf-8', errors='replace'))

  lower = total = seqs = 0
  with op(src) as fin, open('uppercased.fasta', 'w', encoding='utf-8') as out:
      for line in fin:
          if line.startswith('>'):
              seqs += 1
              out.write(line)          # verbatim -- see above
              continue
          s = line.rstrip('\\n')
          total += len(s)
          lower += sum(1 for c in s if 'a' <= c <= 'z')
          out.write(s.upper())
          out.write('\\n')

  if seqs == 0:
      raise SystemExit('no FASTA headers found -- is this a FASTA file?')
  if total == 0:
      raise SystemExit('FASTA contains headers but no sequence')

  frac = lower / total
  print(f'sequences: {seqs:,}')
  print(f'residues:  {total:,}')
  print(f'soft-masked residues removed: {lower:,} ({frac:.1%})')
  if lower == 0:
      print('NOTE: input carried no soft-masking; this was a no-op')
  elif frac > 0.10:
      print(f'NOTE: a substantial existing mask ({frac:.1%}) was discarded. That is intended here '
            f'-- the workflow re-masks from scratch -- and is data loss anywhere else.')
  BRC_PY
inputs:
  - name: input
    type: data
    format: fasta,fasta.gz
    label: Assembly FASTA
    help: plain or gzipped; soft-masked or not
outputs:
  - name: output
    type: data
    format: fasta
    from_work_dir: uppercased.fasta
    label: Uppercased FASTA
help:
  format: markdown
  content: |
    Rewrites every sequence line in uppercase and leaves header lines exactly as they were.

    ⛔ **Why the workflow needs this as a SEPARATE step even though each masker already uppercases
    internally.** The maskers uppercase their own working copy, so the BED tracks are computed on
    unmasked sequence and are correct either way. But `bedtools maskfasta -soft` was applied to the
    ORIGINAL assembly, which lowercases the union intervals *on top of whatever was already
    lowercase*. For an assembly that arrives soft-masked -- cs10 ships **46.8%** masked from NCBI
    genome-wide, which on chromosome 1 is 34.6% of all bases or **47.8% of its non-N bases**,
    while the other assemblies here are 0.0-0.7% -- the published `softmasked_fasta` was then the
    union of this workflow's mask AND NCBI's, indistinguishably. Feeding the uppercased FASTA to
    `maskfasta` makes the output exactly the mask this workflow computed.

    **Reports the fraction it removed**, so a no-op and a discarded 47% mask are distinguishable in
    the job log rather than both looking like success.
"""

    out["samtools_faidx.gxtool.yml"] = HEADER + """class: GalaxyUserTool
id: brc-samtools-faidx
version: "0.1.0"
name: samtools faidx (BRC UDT)
description: Index a FASTA (.fai) and emit the chrom/length table bedtools wants as its genome file
container: quay.io/biocontainers/samtools:1.24--h9dcdb79_1
shell_command: |
  set -o pipefail
""" + DECOMPRESS.replace("upper.fa", "seq.fa").replace(
    "| awk '/^>/{print;next}{print toupper($0)}' ", "") + """
  samtools faidx seq.fa &&
  cut -f1,2 seq.fa.fai > chrom.sizes &&
  awk '/\\r/ && substr($0, length($0), 1) != "\\r" {
      print "⛔ brc-samtools-faidx: a carriage return appears MID-LINE, so this FASTA has lone-CR (classic Mac) or mixed line endings." > "/dev/stderr"
      print "   samtools splits records on a newline exactly as this awk does, so a > that follows a bare CR is invisible to BOTH: the record is swallowed into its predecessor, whose length then covers it, and the record-count guard below sees MATCHING counts and passes." > "/dev/stderr"
      print "   Measured: a 3-record FASTA came out as a 2-row index with the second contig reported 18 bp long when it is 8, and the third absent entirely, exit 0." > "/dev/stderr"
      print "   chrom.sizes is the bedtools genome file WF-C runs on -- an over-long contig lets intervals past its real end survive, and a missing one makes every interval on it vanish. REFUSING; convert the line endings first." > "/dev/stderr"
      exit 1 }' seq.fa &&
  awk '/^>/ {n++} END {print n+0}' seq.fa > n_seq.txt &&
  awk 'END {print NR+0}' seq.fa.fai > n_fai.txt &&
  awk 'NR == FNR {a = $1; next} {b = $1} END {
      if (a+0 == b+0) exit 0
      print "⛔ brc-samtools-faidx: the FASTA holds " a " record(s) and the index " b " row(s)." > "/dev/stderr"
      print "   samtools drops a record in two cases and NEITHER of them changes the exit code:" > "/dev/stderr"
      print "   a DUPLICATE sequence name, which is warning-level only ([W::fai_insert_index]" > "/dev/stderr"
      print "   Ignoring duplicate sequence), and a ZERO-LENGTH record, which says nothing at all." > "/dev/stderr"
      print "   chrom.sizes is the bedtools genome file WF-C runs on, and a contig missing from a" > "/dev/stderr"
      print "   genome file makes every interval on it vanish silently. REFUSING rather than" > "/dev/stderr"
      print "   publishing a short index that looks complete." > "/dev/stderr"
      exit 1 }' n_seq.txt n_fai.txt
inputs:
  - name: input
    type: data
    format: fasta,fasta.gz
    label: FASTA to index
    help: >-
      Plain or gzipped. ⛔ samtools faidx CANNOT index ordinary gzip -- it accepts bgzip and
      nothing else -- so a .gz input is decompressed first rather than passed through. Handed one
      directly it fails with "Cannot index files compressed with gzip, please use bgzip", once per
      element, which is what WF-A did on an NCBI assembly collection: NCBI ships .gz, and unlike
      WF-B (where this step reads the already-decompressed output of brc-fasta-uppercase) WF-A
      indexes the raw assemblies.
outputs:
  - name: output
    type: data
    format: fai
    from_work_dir: seq.fa.fai
    label: FASTA index (.fai)
  - name: sizes
    type: data
    format: tabular
    from_work_dir: chrom.sizes
    label: chrom/length table (bedtools genome file)
help:
  format: markdown
  content: |
    `faidx` is a SUBCOMMAND of samtools, not a separate program, so this wraps the samtools
    biocontainer and calls it.

    **Why this UDT exists at all.** `samtools_faidx` is published in the ToolShed but is NOT
    installed on usegalaxy.org -- a scan of all 2,370 tools in the panel returns no faidx of any
    kind, while twenty other samtools subcommands are present. `workflows/softmask` and
    `workflows/inventory` both reference `tool_id: samtools_faidx`, so both fail at invocation with
    "required tools are not installed" on that step.

    ⚠ **The copy is not redundant.** `samtools faidx` writes `<input>.fai` beside its input, and the
    Galaxy input path is read-only and outside the job's work dir, so indexing in place fails.

    The second output saves a step: the classic workflow ran `Cut c1,c2` over the `.fai` to build
    the bedtools genome file, which is exactly `chrom.sizes` here.
"""

    # ⛔ NOT fastga 1.5. Released 1.5 predates upstream's "ANO file definition change" (0a4a4db,
    # 2026-04-23) and its ANOtoBED cannot open a .1ano written by fastan 0.8 -- it fails at
    # file-open with no hint that a version mismatch is the cause. bioconda-recipes#68612 added
    # 1.5.20260729, which can. See the fastan_bed help text.
    awk_ano = read_helper("tools/fastan/ano2bed6.awk")
    out["fastan_gdb.gxtool.yml"] = HEADER + FASTAN_NOTE + """class: GalaxyUserTool
id: brc-fastan-gdb
version: "0.1.0"
name: FAtoGDB -> GDB tarball (BRC UDT)
description: Convert a FASTA to a FastGA GDB, stage 1 of 3 for the fastan tandem-array track
container: quay.io/biocontainers/fastga:1.5.20260729--h118bc1c_0
shell_command: |
  set -o pipefail
  cp '$(inputs.input.path)' up.fa &&
  FAtoGDB up.fa gdb &&
  tar cf gdb.tar gdb.1gdb .gdb.bps
inputs:
  - name: input
    type: data
    format: fasta
    label: Uppercased FASTA
outputs:
  - name: output
    type: data
    format: data
    from_work_dir: gdb.tar
    label: GDB tarball (gdb.1gdb + .gdb.bps)
help:
  format: markdown
  content: |
    ⛔ **A GDB IS TWO FILES, AND ONE OF THEM IS HIDDEN.** `FAtoGDB x.fa gdb` writes `gdb.1gdb`
    (metadata) *and* `.gdb.bps` (the packed sequence, dot-prefixed). A Galaxy dataset is a single
    file, so the pair is tarred and untarred by stage 2. `tar cf` must name `.gdb.bps` explicitly --
    a glob will not match a dot-file.

    Verified lossless: FasTAN run on an untarred GDB produces BED output byte-identical to FasTAN
    run on the original.

    **Why three tools.** `FAtoGDB` and `ANOtoBED` are in the **fastga** package; `FasTAN` is in
    **fastan**. A UDT gets one container and no mulled fastan+fastga image exists -- confirmed
    against quay.io with galaxy-tool-util's own hashing, with a known-good combination as the
    control (bwa+samtools resolves, this one 401s).
"""

    out["fastan_scan.gxtool.yml"] = HEADER + FASTAN_NOTE + """class: GalaxyUserTool
id: brc-fastan-scan
version: "0.1.0"
name: FasTAN tandem scan (BRC UDT)
description: Find tandem arrays in a GDB, stage 2 of 3
container: quay.io/biocontainers/fastan:0.8--h118bc1c_1
shell_command: |
  set -o pipefail
  cp '$(inputs.gdb.path)' gdb.tar &&
  tar xf gdb.tar &&
  FasTAN -m -p -T1 -oscan gdb
inputs:
  - name: gdb
    type: data
    format: data
    label: GDB tarball from stage 1
outputs:
  - name: output
    type: data
    format: data
    from_work_dir: scan.1ano
    label: tandem annotation (.1ano)
help:
  format: markdown
  content: |
    ⚠ **`-m` REQUIRES A GDB; a FASTA is refused.** `FasTAN` accepts `.fa/.fna/.fasta[.gz]` per its
    usage line, but with masking on it exits *"The source must be a GDB when masking (-m) is on"*.
    That is why stage 1 exists rather than this tool reading the assembly directly.

    ⛔ **`-T1` IS HARDCODED, DELIBERATELY, AND IT IS A PLACEHOLDER.** Three reasons, in order of
    how badly each bites:

    * `$GALAXY_SLOTS` HAS NO FALLBACK HERE. Written bare it is correct on usegalaxy.org (measured:
      the variable is exported, value 1) and collapses to a lone `-T` anywhere it is unset -- at
      which point FasTAN either errors or swallows `-oscan` as its thread count.
      ⚠ An earlier note claimed the classic `${GALAXY_SLOTS:-4}` had "no direct translation"
      because the brace form was fatal in a UDT. THAT WAS WRONG: a backslash-escaped ${GALAXY_SLOTS:-4} escapes
      through to the shell verbatim and yields 1. So a faithful translation does exist -- the pin
      below rests on the two reasons that follow, not on that one.
    * SIBLING TOOLS IN THIS PACKAGE ABORT ABOVE ONE THREAD. FASTAN v0.8's `FastTIR` and `FastLTR`
      die with `free(): double free detected in tcache 2` at any `-T` over 1, including their own
      default of 8. `FasTAN` itself is UNAFFECTED -- measured clean at -T1, -T2 and -T4 -- so this
      line costs it real parallelism. It is pinned anyway so that every tool built on this package
      behaves the same way until the upstream fix ships.
    * A GALAXY THAT GRANTS MORE SLOTS MAKES IT WORSE, NOT BETTER. This repo's own
      `galaxy_config_job_conf.xml` hands every tool 16 slots, so `-T$GALAXY_SLOTS` would be a live
      crash there for the sibling tools while looking fine on the public server.

    Revisit once a fixed FASTAN reaches bioconda; then this becomes `-T$GALAXY_SLOTS` with a
    measured fallback rather than a constant.
"""

    out["fastan_bed.gxtool.yml"] = HEADER + FASTAN_NOTE + f"""class: GalaxyUserTool
id: brc-fastan-bed
version: "0.1.0"
name: ANOtoBED -> BED6 (BRC UDT)
description: Convert a FasTAN annotation to a content-annotated BED6, stage 3 of 3
container: quay.io/biocontainers/fastga:1.5.20260729--h118bc1c_0
shell_command: |
  cat > ano2bed6.awk <<'BRC_AWK'
{indent(awk_ano)}
  BRC_AWK
  set -o pipefail
  cp '$(inputs.ano.path)' scan.1ano &&
  ANOtoBED scan.1ano | {{ grep -v '^#' || [ $? -eq 1 ]; }} | awk -f ano2bed6.awk \\
    | LC_ALL=C sort -k1,1 -k2,2n > annotated.bed6
inputs:
  - name: ano
    type: data
    format: data
    label: .1ano from stage 2
outputs:
  - name: output
    type: data
    format: bed
    from_work_dir: annotated.bed6
    label: tandem-array BED6
help:
  format: markdown
  content: |
    ⛔ **`grep -v` IS GUARDED, AND THE GUARD IS NOT DECORATION.** `grep` exits 1 when it selects no
    lines, `set -o pipefail` is in force, and this is the last command in the tool -- so a sequence
    with NO tandem arrays would fail the job outright when the correct answer is an empty BED6.
    `{{ grep -v ... || [ $? -eq 1 ]; }}` tolerates "nothing matched" while still failing on grep's
    exit 2, which is a real error.

    ⚠ **`ANOtoBED` does NOT need the GDB** -- the sequence names are carried inside the `.1ano`, so
    only stage 2 consumes the tarball. Verified by running it in a directory containing nothing but
    the annotation.

    ⚠ The input is copied to a `.1ano` name first: Galaxy dataset paths end in `.dat`, and the tool
    dispatches on the extension.

    Column 1 is the FIRST WHITESPACE TOKEN of the FASTA header, not the whole description line --
    `ano2bed6.awk` splits it. ANOtoBED emits the entire header, and leaving it would make every
    fastan interval look like a different chromosome to `bedtools merge` than the other maskers'.
"""

    mt = read_helper("tools/masking_table/masking_table.py")
    out["masking_row.gxtool.yml"] = HEADER + f"""class: GalaxyUserTool
id: brc-masking-row
version: "0.2.0"
name: masking table row (BRC UDT)
description: One strain's percent-masked values, to be mapped over the genomecov collections
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > masking_table.py <<'BRC_PY'
{indent(mt)}
  BRC_PY
  set -o pipefail
  python3 masking_table.py \\
    --dustmasker "s=$(inputs.dustmasker.path)" \\
    --windowmasker "s=$(inputs.windowmasker.path)" \\
    --tantan "s=$(inputs.tantan.path)" \\
    --fastan "s=$(inputs.fastan.path)" \\
    --union "s=$(inputs.union.path)" \\
    --out full.tabular &&
  tail -n +2 full.tabular | cut -f2- > row.tabular
inputs:
  - name: dustmasker
    type: data
    format: tabular
    label: dustmasker genomecov for THIS strain
  - name: windowmasker
    type: data
    format: tabular
    label: windowmasker genomecov for THIS strain
  - name: tantan
    type: data
    format: tabular
    label: tantan genomecov for THIS strain
  - name: fastan
    type: data
    format: tabular
    label: fastan genomecov for THIS strain
  - name: union
    type: data
    format: tabular
    label: union genomecov for THIS strain
outputs:
  - name: output
    type: data
    format: tabular
    from_work_dir: row.tabular
    label: percent masked, one strain (values only)
help:
  format: markdown
  content: |
    ⛔ **THIS TOOL DELIBERATELY DOES NOT KNOW WHICH STRAIN IT IS PROCESSING**, and that is the whole
    design. The classic `masking_table` reads `$el.element_identifier` across five whole
    collections. The obvious port is to map one job per strain and have each read its own
    identifier as `$(inputs["<name>|__identifier__"])` -- and that WORKS when a UDT is mapped
    through the tool API, which is how it was first verified. It FAILS inside a workflow: the same
    tool, the same collection, mapped by the workflow engine instead, dies with "Error occurred
    while building command line for tool", naming nothing.

    So the sample name is supplied by Galaxy instead. `Collapse Collection` with
    `filename|add_name=true` and `place_name=same_multiple` prepends each element's IDENTIFIER to
    its lines, which is exactly the Sample column. This tool therefore emits only the numbers, and
    the header is added afterwards by `brc-masking-header`.

    ⚠ `masking_table.py` is inlined VERBATIM from `tools/masking_table/`, so the percentages are
    computed by the same code as the classic tool. The dummy `s=` key and the `tail -n +2 | cut -f2-`
    strip its header and its own Sample column; nothing about the arithmetic is reimplemented.
"""

    out["masking_header.gxtool.yml"] = HEADER + """class: GalaxyUserTool
id: brc-masking-header
version: "0.1.0"
name: masking table header (BRC UDT)
description: Prepend the Sample/masker header to the collapsed per-strain rows
container: quay.io/biocontainers/python:3.12
shell_command: |
  set -o pipefail
  printf 'Sample\\tdustmasker\\twindowmasker\\ttantan\\tfastan\\tunion\\n' > table.tabular &&
  cat '$(inputs.rows.path)' >> table.tabular
inputs:
  - name: rows
    type: data
    format: tabular
    label: collapsed per-strain rows, strain already prepended
outputs:
  - name: output
    type: data
    format: tabular
    from_work_dir: table.tabular
    label: Sample x masker percent-masked table
help:
  format: markdown
  content: |
    A header line, and nothing else. It exists because the two steps that could have supplied one
    each cannot:

    * `brc-masking-row` runs once per strain, so a header emitted there would repeat per row.
    * `Collapse Collection`'s `one_header` keeps the first element's header -- but only if every
      element HAS one, and prepending the strain name would corrupt that first cell into the strain
      rather than `Sample`.

    ⚠ The column order is fixed here and must match the order `masking_table.py` writes, which is
    the order its `maskers` list defines: dustmasker, windowmasker, tantan, fastan, union. A change
    there without a change here would mislabel every column and nothing would fail.

    The header is plain, with no leading `#`, so MultiQC custom-content reads it as a table rather
    than mis-parsing it as embedded YAML.
"""

    lc = read_helper("tools/dustmasker/lc_classify.py")
    out["lc_classify.gxtool.yml"] = HEADER + SPLIT_NOTE + f"""class: GalaxyUserTool
id: brc-lc-classify
version: "0.1.0"
name: lc_classify -> BED6 (BRC UDT)
description: Annotate masked intervals with repeat-unit signature and purity, stage 2 of 2
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > lc_classify.py <<'BRC_PY'
{indent(lc)}
  BRC_PY
  set -o pipefail
  python3 lc_classify.py '$(inputs.fasta.path)' '$(inputs.intervals.path)' \\
    | LC_ALL=C sort -k1,1 -k2,2n > annotated.bed6
inputs:
  - name: fasta
    type: data
    format: fasta
    label: Uppercased FASTA
    help: the `upper_fasta` output of the matching stage-1 masker, NOT the original assembly
  - name: intervals
    type: data
    format: bed
    label: BED3 intervals
    help: the `intervals` output of the matching stage-1 masker
outputs:
  - name: output
    type: data
    format: bed
    from_work_dir: annotated.bed6
    label: content-annotated BED6
help:
  format: markdown
  content: |
    Stage 2 of the two-step masker port, shared by dustmasker, windowmasker and tantan.

    Column 4 carries the repeat-unit signature (`polyA`, `(AT)n`, or `lc`), column 5 the purity
    x1000 driving UCSC grayscale, column 6 `.`. This is `tools/dustmasker/lc_classify.py` inlined
    verbatim, not a reimplementation.
"""
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if a committed file differs from what would be generated")
    args = ap.parse_args()

    assert_sources_aligned()
    UDT.mkdir(exist_ok=True)
    stale = []
    for fn, body in build().items():
        path = UDT / fn
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if args.check:
            if current != body:
                stale.append(fn)
            continue
        path.write_text(body, encoding="utf-8")
        print(f"  {'unchanged' if current == body else 'wrote':>9} udt/{fn}")
    # ⛔ ORPHANS ARE INVISIBLE TO A GENERATED-SIDE CHECK. --check iterates build() and never looks
    # at what is on disk, so a UDT that build() no longer produces -- because its key was renamed,
    # or it was hand-written and never generated at all -- is never compared to anything and stays
    # deployable and stale. `udt/env_probe.gxtool.yml` is live proof: committed, registerable, and
    # never generated. Renaming a key is worse: --check correctly reports the NEW file stale, you
    # regenerate as instructed, and the OLD one is left behind still referenced by the workflow.
    generated = set(build())
    on_disk = {p.name for p in UDT.glob("*.gxtool.yml")}
    # ⚠ A CONVERTED UDT IS NOT AN ORPHAN, IT IS CHECKED SOMEWHERE ELSE. udt/ also holds documents
    # emitted by the fork-side converter, which stamps each one with a `# provenance:` block naming
    # its source wrapper and the hashes of that wrapper's <command> and macros.xml.
    # scripts/check_udt_provenance.py verifies those with the standard library. This exemption is
    # DERIVED from the stamp rather than listed by hand, so a new converted UDT needs no edit here
    # -- and the count is printed, so "no orphans" can never quietly mean "nothing was examined".
    # ⚠ AND A UDT FROM ANOTHER GENERATOR IS NOT AN ORPHAN EITHER. `build_inventory_udts.py` emits
    # the WF-A bookkeeping tools and carries its own --check. Both exemptions are DERIVED from what
    # the file says about itself -- a `# provenance:` stamp, or a "GENERATED by" line naming a
    # different generator -- so neither needs an edit here when a new one is added.
    converted = set()
    for path in UDT.glob("*.gxtool.yml"):
        head = path.read_text(encoding="utf-8")[:600]
        if "# provenance:" in head or ("GENERATED by scripts/" in head and "build_softmask_udts.py" not in head.split("\n")[0]):
            converted.add(path.name)
    if converted:
        print(f"  {len(converted)} UDT(s) checked elsewhere (provenance stamp or another "
              f"generator): {', '.join(sorted(converted))}")
    # ⛔ MEMBERSHIP IS ONLY EVER SUBTRACTED, SO A DECLARED FILE THAT NO LONGER EXISTS IS INVISIBLE.
    # Deleting a hand-written UDT left --check green and still printing "4 hand-written", because
    # that number is len(HAND_WRITTEN_UDTS) -- a set size, not a disk count. The orphan check's own
    # rationale is that "no orphans" should be a real statement; it was vacuous in this direction.
    missing = sorted(HAND_WRITTEN_UDTS - on_disk)
    if missing:
        sys.exit(f"REFUSING: {len(missing)} UDT(s) are declared HAND_WRITTEN but absent from "
                 f"udt/: {missing}. Either the file was deleted and the entry should go with it, "
                 f"or the entry is a typo and the real file is an unchecked orphan.")

    orphans = sorted(on_disk - generated - HAND_WRITTEN_UDTS - converted)
    if orphans:
        for fn in orphans:
            print(f"  ORPHAN udt/{fn} — on disk, not produced by build(), never checked")
        print("  Delete it, add it to build(), or list it in HAND_WRITTEN_UDTS with a reason.")
        if args.check:
            return 1

    if args.check:
        for fn in stale:
            print(f"  STALE udt/{fn}")
        if stale:
            print("  Regenerate with: python3 scripts/build_softmask_udts.py")
            return 1
        print(f"  all committed UDTs match their sources ({len(generated)} generated, "
              f"{len(HAND_WRITTEN_UDTS)} hand-written, {len(converted)} converted)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
