#!/usr/bin/env python3
"""Generate the WF-A bookkeeping UDTs from the helper scripts under `tools/`.

`collection_self_pairs` and `collection_relabel_map` cannot be ported as they stand, and the reason
is architectural rather than fixable by translation: their `<command>` reads
`$el.element_identifier` across a whole collection, and a job receives PATHS -- identifiers do not
reach it by any route. The refusal our converter prints says "restructure the tool to run once per
element"; this is the restructuring, and it is smaller than that.

⚠ THE UNLOCK IS AN IUC TOOL usegalaxy.org ALREADY INSTALLS.
`toolshed.g2.bx.psu.edu/repos/iuc/collection_element_identifiers` turns a list collection into a
text file of its element identifiers, one per line. Put that in front and both helpers become
ordinary file-in/file-out tools -- the identifiers arrive as DATA, which a container can read.

⛔ THE PYTHON IS NOT REWRITTEN HERE, IT IS INLINED VERBATIM from `tools/`. The classic wrappers keep
running it on a local Galaxy; if this file paraphrased the logic instead, the two copies would drift
and the UDT edition would quietly compute something else -- the failure mode this whole port is
supposed to avoid. Only the ARGUMENT SHAPE changes: `--ids` receives the file's contents rather than
a Cheetah-interpolated list.

    python3 scripts/build_inventory_udts.py           # write udt/
    python3 scripts/build_inventory_udts.py --check   # non-zero if the committed copies are stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
UDT = ROOT / "udt"

HEADER = """# ⛔ GENERATED by scripts/build_inventory_udts.py -- do not hand-edit.
# The Python below is inlined VERBATIM from the wrapper's helper under tools/; edit it there and
# regenerate. Only the argument shape differs from the classic tool: the element identifiers arrive
# as a FILE (from the IUC collection_element_identifiers tool) rather than as a Cheetah-interpolated
# list, because a job container receives paths and never sees a collection's identifiers.
"""


#: UDT-only glue with NO classic counterpart, which is why it lives here rather than under tools/.
#:
#: ⛔ IT EXISTS BECAUSE A COLLECTION INPUT CARRIES NO IDENTITY. Measured on usegalaxy.org
#: (udt/collection_probe.gxtool.yml): `$(inputs.x)` renders a list of File records whose `basename`
#: is the DATASET name -- both elements of a two-element list read `chrom.sizes` -- while the
#: element identifiers appear nowhere. ORDER survives, identity does not. sourmash's matrix labels
#: ARE the strain names, so the identifiers have to arrive separately and be paired by position.
#:
#: ⚠ AND PAIRING BY POSITION IS ONLY SAFE IF IT IS CHECKED. A mismatch would relabel every row of
#: the similarity matrix silently -- the worst failure this pipeline can produce, because the output
#: still looks like a result. So the count is asserted before anything is sketched, and each
#: signature's name is written into the .sig by sourmash itself.
SOURMASH_GLUE = """#!/usr/bin/env python3
\"\"\"Sketch every assembly in a collection, then compare -- labelling by element identifier.

The identifiers cannot be read from the collection inside a job (see the module docstring of
scripts/build_inventory_udts.py); they are supplied as a file, in collection order.
\"\"\"
import argparse
import re
import subprocess
import sys

ap = argparse.ArgumentParser()
ap.add_argument("--rendered", required=True, help="file holding the rendered collection input")
ap.add_argument("--ids", required=True, help="element identifiers, one per line, in collection order")
ap.add_argument("--ksize", default="31")
ap.add_argument("--scaled", default="1000")
a = ap.parse_args()

paths = re.findall(r"path:\\s*([^,}\\s]+)", open(a.rendered).read())
ids = [x.strip() for x in open(a.ids) if x.strip()]

# ⛔ THE ASSERTION IS THE POINT. Pairing by position is correct only while the two lists describe
# the same collection; if they do not, every row of the matrix is mislabelled and nothing
# downstream can tell. Refuse instead.
if len(paths) != len(ids):
    sys.exit(f"refusing to guess: {len(paths)} assemblies but {len(ids)} identifiers. "
             f"The identifier file must come from the SAME collection, via the IUC "
             f"collection_element_identifiers tool.")
if not paths:
    sys.exit("no assemblies in the collection input")

subprocess.run(["mkdir", "-p", "stage"], check=True)
for path, name in zip(paths, ids):
    sig = f"stage/{name}.sig"
    subprocess.run(["sourmash", "sketch", "dna", "-p", f"k={a.ksize},scaled={a.scaled}",
                    "--name", name, "-o", sig, path], check=True)
    print(f"sketched {name} <- {path}", file=sys.stderr)

sigs = [f"stage/{n}.sig" for n in ids]
subprocess.run(["sourmash", "compare", "--ksize", a.ksize, "-o", "cmp", "--csv", "similarity.csv",
                *sigs], check=True)
subprocess.run(["sourmash", "plot", "--labels", "cmp"], check=True)
"""

#: (udt stem, tool id, helper path, tool name, description, output format, output label)
TOOLS = (
    ("self_pairs", "brc-self-pairs", "tools/collection_self_pairs/self_pairs.py",
     "self-pair ids from element identifiers (BRC UDT)",
     "Emit one {id}_{id} line per identifier, to drop the self-cross diagonal in WF-C",
     "txt", "self-pair ids (X_X), one per line"),
    ("relabel_map", "brc-relabel-map", "tools/collection_relabel_map/relabel_map.py",
     "relabel map from element identifiers (BRC UDT)",
     "Emit {a}_{b}<TAB>{a}.{b} for every ordered pair, to rename WF-C's cross-product cells",
     "tabular", "A_B -> A.B relabel map (2-column TSV)"),
)


def build() -> dict[str, str]:
    out: dict[str, str] = {}
    out["sourmash_panel.gxtool.yml"] = sourmash_udt()
    for stem, tool_id, helper, name, description, ext, label in TOOLS:
        script = (ROOT / helper).read_text(encoding="utf-8").rstrip("\n")
        indented = "\n".join(f"  {ln}" if ln else "" for ln in script.splitlines())
        out[f"{stem}.gxtool.yml"] = HEADER + f"""class: GalaxyUserTool
id: {tool_id}
version: "0.1.0"
name: {name}
description: {description}
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > {stem}.py <<'BRC_PY'
{indented}
  BRC_PY
  python3 {stem}.py --ids "$(tr '\\n' ' ' < '$(inputs.identifiers.path)')" --out {stem}.{ext}
inputs:
  - name: identifiers
    type: data
    format: txt
    label: element identifiers, one per line
    help: >-
      The output of the IUC "Extract element identifiers" tool run on the collection this is about.
      A job container cannot see a collection's identifiers, so they have to arrive as data.
outputs:
  - name: output
    type: data
    format: {ext}
    from_work_dir: {stem}.{ext}
    label: {label}
help:
  format: markdown
  content: |
    Same logic as the classic `{helper.split("/")[1]}` tool -- the Python is inlined from
    `{helper}` verbatim by `scripts/build_inventory_udts.py`, so the two cannot drift.

    **What changed is the input, and only because it had to.** The classic wrapper interpolates
    `$el.element_identifier` over the collection at command-build time. A user-defined tool gets one
    container and a set of PATHS; the identifiers are not available to it by any route. So the
    identifiers arrive as a file, produced by the IUC `collection_element_identifiers` tool, which
    usegalaxy.org installs.

    ⚠ **Feed it the SAME collection the pairs are about.** Nothing downstream can detect a mismatch:
    a self-pair list built from the wrong collection removes nothing, and a relabel map built from
    the wrong one renames nothing, both silently.
"""
    return out



def sourmash_udt() -> str:
    """The one-job sourmash port: sketch every assembly, then compare, labelled by identifier."""
    indented = "\n".join(f"  {ln}" if ln else "" for ln in SOURMASH_GLUE.rstrip("\n").splitlines())
    return HEADER + f"""class: GalaxyUserTool
id: brc-sourmash-panel
version: "0.1.0"
name: sourmash sketch + compare over a panel (BRC UDT)
description: MinHash signatures for every assembly in a collection and the similarity matrix over them
container: quay.io/biocontainers/sourmash:4.9.4--hdfd78af_0
shell_command: |
  cat > rendered.txt <<'BRC_RENDERED'
  $(inputs.assemblies)
  BRC_RENDERED
  cat > sourmash_panel.py <<'BRC_PY'
{indented}
  BRC_PY
  python3 sourmash_panel.py --rendered rendered.txt --ids '$(inputs.identifiers.path)' --ksize '$(inputs.ksize)'
inputs:
  - name: assemblies
    type: data_collection
    collection_type: list
    label: assemblies to sketch
    help: The panel. One signature per element, sketched in collection order.
  - name: identifiers
    type: data
    format: txt
    label: element identifiers of THAT collection, one per line
    help: >-
      From the IUC "Extract element identifiers" tool, run on the same collection. A job cannot read
      a collection's identifiers, and sourmash's matrix labels are the strain names, so they are
      supplied here and paired by position -- with the count asserted before anything is sketched.
  - name: ksize
    type: integer
    value: 31
    label: k-mer size
outputs:
  - name: similarity
    type: data
    format: csv
    from_work_dir: similarity.csv
    label: sourmash similarity matrix (CSV, labelled by strain)
  - name: heatmap
    type: data
    format: png
    from_work_dir: cmp.matrix.png
    label: sourmash clustered heatmap
  - name: dendrogram
    type: data
    format: png
    from_work_dir: cmp.dendro.png
    label: sourmash dendrogram
help:
  format: markdown
  content: |
    Both halves of the classic WF-A pair -- `sourmash_sketch` mapped over the panel and
    `sourmash_compare` over the resulting signatures -- in ONE job.

    ⚠ **That is not a shortcut, it is what the platform allows.** A user-defined tool cannot read a
    collection's element identifiers: measured on usegalaxy.org, `$(inputs.x)` renders File records
    whose `basename` is the DATASET name, with the identifiers nowhere in them. sourmash's matrix
    labels are the strain names, so the identifiers must be supplied alongside and paired by
    position — and pairing by position across two workflow steps would be a silent relabelling
    hazard. Sketching and comparing in one job keeps the pairing inside a single assertion.

    ⛔ **The assertion is the point.** If the identifier count and the assembly count disagree, the
    job REFUSES rather than sketching. A mismatched pair would produce a similarity matrix that is
    fully populated, plausible, and wrong about which strain each row is.

    The signature names are written by `sourmash sketch --name`, so the labels in the CSV come from
    the sketches themselves rather than from a post-hoc rename.
"""

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare against udt/ and exit non-zero if any committed copy is stale")
    args = ap.parse_args()

    stale = []
    for filename, body in build().items():
        path = UDT / filename
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != body:
                stale.append(filename)
            continue
        path.write_text(body, encoding="utf-8")
        print(f"  {'unchanged' if current == body else 'wrote':>9} udt/{filename}")

    if args.check:
        for filename in stale:
            print(f"  STALE udt/{filename}")
        if stale:
            print("  Regenerate with: python3 scripts/build_inventory_udts.py")
            return 1
        print(f"  all committed inventory UDTs match their helpers ({len(build())} generated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
