#!/usr/bin/env python3
"""Generate the WF-A bookkeeping UDTs from the helper scripts under `tools/`.

`collection_self_pairs` and `collection_relabel_map` cannot be ported as they stand, and the reason
is architectural rather than fixable by translation: their `<command>` reads
`$el.element_identifier` across a whole collection, and a job receives PATHS -- identifiers do not
reach it by any route. The refusal our converter prints says "restructure the tool to run once per
element"; this is the restructuring, and it is smaller than that.

⚠ THE UNLOCK IS AN IUC TOOL usegalaxy.org ALREADY INSTALLS.
`toolshed.g2.bx.psu.edu/repos/iuc/collection_element_identifiers` turns a list collection into a
text file of its element identifiers, one per line. Put that in front and both helpers become
ordinary file-in/file-out tools -- the identifiers arrive as DATA, which a container can read.

⛔ THE PYTHON IS NOT REWRITTEN HERE, IT IS INLINED VERBATIM from `tools/`. The classic wrappers keep
running it on a local Galaxy; if this file paraphrased the logic instead, the two copies would drift
and the UDT edition would quietly compute something else -- the failure mode this whole port is
supposed to avoid. Only the ARGUMENT SHAPE changes: `--ids` receives the file's contents rather than
a Cheetah-interpolated list.

    python3 scripts/build_inventory_udts.py           # write udt/
    python3 scripts/build_inventory_udts.py --check   # non-zero if the committed copies are stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
UDT = ROOT / "udt"

HEADER = """# ⛔ GENERATED by scripts/build_inventory_udts.py -- do not hand-edit.
# The Python below is inlined VERBATIM from the wrapper's helper under tools/; edit it there and
# regenerate. Only the argument shape differs from the classic tool: the element identifiers arrive
# as a FILE (from the IUC collection_element_identifiers tool) rather than as a Cheetah-interpolated
# list, because a job container receives paths and never sees a collection's identifiers.
"""


#: UDT-only glue with NO classic counterpart, which is why it lives here rather than under tools/.
#:
#: ⛔ IT EXISTS BECAUSE A COLLECTION INPUT CARRIES NO IDENTITY. Measured on usegalaxy.org
#: (udt/collection_probe.gxtool.yml): `$(inputs.x)` renders a list of File records whose `basename`
#: is the DATASET name -- both elements of a two-element list read `chrom.sizes` -- while the
#: element identifiers appear nowhere. ORDER survives, identity does not. sourmash's matrix labels
#: ARE the strain names, so the identifiers have to arrive separately and be paired by position.
#:
#: ⚠ AND PAIRING BY POSITION IS ONLY SAFE IF IT IS CHECKED. A mismatch would relabel every row of
#: the similarity matrix silently -- the worst failure this pipeline can produce, because the output
#: still looks like a result. So the count is asserted before anything is sketched, and each
#: signature's name is written into the .sig by sourmash itself.
SOURMASH_GLUE = """#!/usr/bin/env python3
\"\"\"Sketch every assembly in a collection, then compare -- labelling by element identifier.

The identifiers cannot be read from the collection inside a job (see the module docstring of
scripts/build_inventory_udts.py); they are supplied as a file, in collection order.
\"\"\"
import argparse
import json
import re
import subprocess
import sys

ap = argparse.ArgumentParser()
ap.add_argument("--rendered", required=True, help="file holding the rendered collection input")
ap.add_argument("--ids", required=True, help="element identifiers, one per line, in collection order")
ap.add_argument("--ksize", default="31")
ap.add_argument("--scaled", default="1000")
a = ap.parse_args()

# ⛔ THE KEYS ARE QUOTED. Galaxy renders a collection input as JSON -- {"path": "/..."} -- not as a
# JavaScript object literal, so a pattern written for a bare path key matches NOTHING and this
# script reported "0 assemblies" against a perfectly good render: the heredoc held six well-formed
# File records and every one was missed, which is why WF-A could never sketch anything. Parse it as
# JSON, and fall back to the pattern only if that fails, so a future change in render shape
# degrades loudly instead of silently finding zero.
_raw = open(a.rendered).read()
_json_ok = True
try:
    _recs = json.loads(_raw[_raw.index("["):_raw.rindex("]") + 1])
    paths = [r["path"] for r in _recs if isinstance(r, dict) and r.get("path")]
except Exception:
    # ⚠ THE FALLBACK IS A DIAGNOSTIC, NOT A SECOND PARSER. Once it scraped even ONE path the
    # render fault below stopped firing and the count check took over -- so a render shaped
    # {"class":"File","path":...} instead of a list, which is exactly the "future change in render
    # shape" this fallback anticipates, was reported as "1 assemblies but 2 identifiers. The
    # identifier file must come from the SAME collection" and sent the operator to inspect the one
    # input that was correct. Remember that the JSON parse failed, and say so.
    _json_ok = False
    paths = re.findall(r'"?path"?\\s*:\\s*"?([^",}\\s]+)', _raw)
# ⚠ utf-8-SIG, NOT utf-8, and the same identifier checks the two sibling helpers already make.
# A BOM survives `.strip()` and lands in the first name, so the matrix comes out labelled
# `\ufeffcs10` -- which then joins against nothing in the self-pair or relabel files built from the
# SAME file. Measured. A tab is rejected there and was accepted here; the CSV header took it.
ids = [x.strip() for x in open(a.ids, encoding="utf-8-sig") if x.strip()]
_bad = [i for i in ids if "\t" in i]
if _bad:
    sys.exit(f"identifier(s) contain a tab, which lands in the similarity matrix header and breaks "
             f"every column contract downstream: {_bad[:3]}")

# ⛔ THE ASSERTION IS THE POINT. Pairing by position is correct only while the two lists describe
# the same collection; if they do not, every row of the matrix is mislabelled and nothing
# downstream can tell. Refuse instead.
# ⛔ DIAGNOSE THE RENDER BEFORE BLAMING THE IDENTIFIERS. This comparison used to run first, so an
# unparseable or empty rendered block reported "0 assemblies but N identifiers -- the identifier file
# must come from the SAME collection", pointing the operator at the one input that was correct. A
# render this cannot read is a DIFFERENT fault and says so.
if not _json_ok or not paths:
    sys.exit(f"could not parse the rendered collection input as JSON; the fallback pattern "
             f"scraped {len(paths)} path(s). That is a "
             "RENDER problem, not an identifier problem -- the identifier file is not implicated. "
             "The block should be a JSON array of File records; check what the tool actually "
             "received before changing anything about the identifiers.")
# ⛔ DUPLICATE IDENTIFIERS SILENTLY DESTROY A ROW. Each signature is staged at `stage/{name}.sig`,
# so two elements sharing a name overwrite one file -- and the count assertion below still passes,
# because the COUNTS match. The result is a fully populated matrix in which one genome does not
# appear and another appears twice, which is exactly the "runs and mislabels its output" failure
# this script's assertions exist to prevent.
if len(set(ids)) != len(ids):
    _dupes = sorted({i for i in ids if ids.count(i) > 1})
    sys.exit(f"duplicate element identifier(s) {_dupes[:3]}: a repeat would put two genomes in one "
             f"row of the matrix. Counts alone cannot detect this.")
# ⚠ AND THESE NAMES ARE STILL REFUSED, THOUGH THE REASON HAS CHANGED. While signatures were staged
# at `stage/{name}.sig` this was a data-loss guard: `gA` and `./gA` are distinct strings naming the
# SAME file, so one sketch overwrote the other, the matrix came out `./gA,./gA` with an
# off-diagonal 1.0 that is a self-comparison, and a genome was absent -- exit 0. `../escaped` wrote
# the signature outside the job directory. Staging by INDEX (below) removed both hazards outright.
# What is left is narrower and worth keeping anyway: such a name still travels into `--name` and
# becomes a COLUMN LABEL in similarity.csv, where a leading dash or an embedded path reads as a
# malformed strain and joins against nothing downstream. Refusing early says so; it is no longer
# the difference between a correct matrix and a corrupt one.
_bad = [i for i in ids if "/" in i or i in (".", "..") or i.startswith("-")]
if _bad:
    sys.exit(f"element identifier(s) {_bad[:3]} contain a path separator, are a directory alias, or "
             f"begin with a dash. Galaxy allows them; this tool will not stage them, because such a "
             f"name can silently overwrite another element's signature or write outside the job.")
if len(paths) != len(ids):
    sys.exit(f"refusing to guess: {len(paths)} assemblies but {len(ids)} identifiers. "
             f"The identifier file must come from the SAME collection, via the IUC "
             f"collection_element_identifiers tool.")
subprocess.run(["mkdir", "-p", "stage"], check=True)
for _i, (path, name) in enumerate(zip(paths, ids)):
    sig = f"stage/{_i:04d}.sig"
    subprocess.run(["sourmash", "sketch", "dna", "-p", f"k={a.ksize},scaled={a.scaled}",
                    "--name", name, "-o", sig, path], check=True)
    # ⛔ AN EMPTY SKETCH IS INDISTINGUISHABLE FROM AN UNRELATED GENOME, AND sourmash SAYS NOTHING.
    # At --scaled 1000 a small enough sequence contributes NO hashes: measured, a 500 bp assembly
    # and 180 kb of N both sketched to 0 mins, and the similarity.csv that came out was
    # BYTE-IDENTICAL to the run where that element was a genuine 200 kb unrelated genome -- row
    # `0.0, 1.0, 0.0`, exit 0. So a panel member that failed upstream, or any small-genome member
    # (an organelle, a plasmid, an apicoplast), reads as "shares nothing with anyone" and this
    # matrix feeds WF-I's fold order. The count assertion above cannot see it; only the hashes can.
    _n = sum(len(s.get("mins") or []) for rec in json.load(open(sig))
             for s in (rec.get("signatures") or []))
    # ⚠ AND THE BOUNDARY IS NOT ZERO. The harm this describes -- a row that reads "shares nothing
    # with anyone" -- is a property of a SMALL sketch, not of an empty one. Measured at
    # scaled=1000, k=31: a 360 nt viroid gives 1 hash, a 2 kb plasmid 3, a 5 kb virus 7, and each
    # of their similarity rows is BYTE-IDENTICAL to a genuinely unrelated 200 kb genome's. Worse,
    # a 30 kb truncation of a 3 Mb assembly -- 19 hashes, 100% contained in it -- scored 0.0064
    # against its own parent, indistinguishable from 0.0 in a heatmap and in WF-I's fold order.
    # Refusing at 0 and waving through 1 draws the line in the one place it does not belong.
    _floor = max(20, int(a.scaled) // 50)
    if _n == 0:
        sys.exit(f"{name} sketched to ZERO hashes at scaled={a.scaled}, so it can only appear in "
                 f"the matrix as a genome sharing nothing with anyone -- which is not a failure "
                 f"the run would otherwise report. Lower --scaled, or drop the element. ⚠ It is "
                 f"N-masking that empties a sketch, NOT soft-masking: a 200 kb genome in "
                 f"all-lowercase gives 195 hashes, measured.")
    if _n < _floor:
        print(f"⚠ {name} sketched only {_n} hash(es) at scaled={a.scaled} (floor {_floor}). Its "
              f"row will look like an unrelated genome's whatever it actually is -- a 5 kb genome "
              f"at 7 hashes is byte-identical in the matrix to something that shares nothing. "
              f"Treat its similarities as unmeasured, or lower --scaled for the whole panel.",
              file=sys.stderr)
    print(f"sketched {name} <- {path}  ({_n} hashes)", file=sys.stderr)

sigs = [f"stage/{i:04d}.sig" for i in range(len(ids))]
subprocess.run(["sourmash", "compare", "--ksize", a.ksize, "-o", "cmp", "--csv", "similarity.csv",
                *sigs], check=True)
subprocess.run(["sourmash", "plot", "--labels", "cmp"], check=True)
"""

#: (udt stem, tool id, helper path, tool name, description, output format, output label)
TOOLS = (
    ("self_pairs", "brc-self-pairs", "tools/collection_self_pairs/self_pairs.py",
     "self-pair ids from element identifiers (BRC UDT)",
     "Emit one {id}_{id} line per identifier, to drop the self-cross diagonal in WF-C",
     "txt", "self-pair ids (X_X), one per line"),
    ("relabel_map", "brc-relabel-map", "tools/collection_relabel_map/relabel_map.py",
     "relabel map from element identifiers (BRC UDT)",
     "Emit {a}_{b}<TAB>{a}.{b} for every ordered pair, to rename WF-C's cross-product cells",
     "tabular", "A_B -> A.B relabel map (2-column TSV)"),
)


#: ⚠ Galaxy interpolates `$(...)` ANYWHERE in `shell_command`, heredocs included, so a NESTED
#: `$(...)` -- shell command substitution wrapped around a Galaxy expression -- is consumed as a
#: Galaxy expression and the command line cannot be built. scripts/build_softmask_udts.py has
#: refused this since it was written; this generator emitted it in two tools, and neither had ever
#: run. Assert on the RENDERED text, which is the only place the mistake is visible.
#: ⚠ Galaxy interpolates this two-character opener ANYWHERE in a shell_command, heredocs
#: included. scripts/build_softmask_udts.py has refused it in helper bodies since it was
#: written; this generator did not, and shipped two tools that could never build a command.
FORBIDDEN = "$("


def assert_no_nested_substitution(rendered: dict[str, str]) -> None:
    """Refuse any `$(` nested inside another `$(` in a tool's shell_command.

    ⛔ WHY THIS MATTERS: Galaxy owns `$(...)` in a shell_command and interpolates it ANYWHERE,
    heredocs included, so a shell command substitution wrapped around a Galaxy expression has its
    OUTER form eaten and the job dies at command-build with an empty command line -- measured on
    both 26.1 and 25.0. The documented escape for a literal shell substitution is `\\$(...)`.

    ⚠ A REGEX CANNOT DO THIS, AND THE FIRST VERSION TRIED. `\\$\\((?:[^()]*\\$\\()` requires the two
    openers to have NO parenthesis between them, so every one of these slipped through -- each the
    exact construct the guard exists to refuse:
        $( (cat) ; cat '$(inputs.x.path)')
        $(tr -d '()' < '$(inputs.x.path)')
        $(python3 -c 'print(0)' '$(inputs.x.path)')
    Scan with a depth counter instead.

    ⚠ AND IT MUST READ shell_command ONLY. Run over the whole rendered YAML it also saw `help:`
    prose, so any two mentions of the opener with no `)` between them failed the build -- which is
    why two helper scripts carry a note telling their own authors not to write the sequence down.
    A guard that shapes the documentation away from naming the hazard is doing harm.
    """
    import yaml as _yaml
    for name, text in rendered.items():
        cmd = (_yaml.safe_load(text) or {}).get("shell_command") or ""
        i = 0
        while (i := cmd.find("$(", i)) != -1:
            if i and cmd[i - 1] == "\\":          # the documented escape: passed to the shell
                i += 2
                continue
            depth, j = 0, i
            while j < len(cmd):
                if cmd[j] == "(":
                    depth += 1
                elif cmd[j] == ")":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            inner = cmd[i + 2:j]
            k = inner.find("$(")
            if k != -1 and (k == 0 or inner[k - 1] != "\\"):
                line = cmd[:i].count("\n") + 1
                raise SystemExit(
                    f"REFUSING: {name} shell_command line {line} nests `$(` inside `$(`. Galaxy "
                    f"interpolates the outer one as an expression and the job fails with an empty "
                    f"command line before anything runs. Pass the PATH and let the inlined script "
                    f"read the file, or escape a literal shell substitution as \\$(...).")
            i = j + 1


def build() -> dict[str, str]:
    out: dict[str, str] = {}
    # ⛔ SOURMASH_GLUE IS INLINED INTO THE SAME HEREDOC AND WAS CHECKED BY NOTHING. The FORBIDDEN
    # test below covers helpers read from tools/; this constant is not read from tools/, so a `$(`
    # added to it would have been shipped. Same body, same hazard, same check.
    if FORBIDDEN in SOURMASH_GLUE:
        raise SystemExit(f"REFUSING: SOURMASH_GLUE contains `{FORBIDDEN}`, which Galaxy would "
                         f"interpolate inside the heredoc. Describe the sequence, do not write it.")
    out["sourmash_panel.gxtool.yml"] = sourmash_udt()
    for stem, tool_id, helper, name, description, ext, label in TOOLS:
        script = (ROOT / helper).read_text(encoding="utf-8").rstrip("\n")
        # ⛔ THE SAME CHECK build_softmask_udts.read_helper MAKES, AND FOR THE SAME REASON. Galaxy
        # interpolates the two-character opener ANYWHERE in a shell_command, heredocs included, so
        # a helper carrying one -- even inside a comment or an f-string -- is rewritten on its way
        # into the tool. assert_no_nested_substitution below only sees the NESTED form; a bare one
        # inlined from tools/ passes it and fails at command-build time with an empty command.
        if FORBIDDEN in script:
            raise SystemExit(
                f"REFUSING: {helper} contains `{FORBIDDEN}`, which Galaxy would interpolate inside "
                f"the heredoc, corrupting the inlined script. Describe the sequence, do not write it.")
        indented = "\n".join(f"  {ln}" if ln else "" for ln in script.splitlines())
        out[f"{stem}.gxtool.yml"] = HEADER + f"""class: GalaxyUserTool
id: {tool_id}
version: "0.1.0"
name: {name}
description: {description}
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > {stem}.py <<'BRC_PY'
{indented}
  BRC_PY
  python3 {stem}.py --ids-file '$(inputs.identifiers.path)' --out {stem}.{ext}
inputs:
  - name: identifiers
    type: data
    format: txt
    label: element identifiers, one per line
    help: >-
      The output of the IUC "Extract element identifiers" tool run on the collection this is about.
      A job container cannot see a collection's identifiers, so they have to arrive as data.
outputs:
  - name: output
    type: data
    format: {ext}
    from_work_dir: {stem}.{ext}
    label: {label}
help:
  format: markdown
  content: |
    Same logic as the classic `{helper.split("/")[1]}` tool -- the Python is inlined from
    `{helper}` verbatim by `scripts/build_inventory_udts.py`, so the two cannot drift.

    **What changed is the input, and only because it had to.** The classic wrapper interpolates
    `$el.element_identifier` over the collection at command-build time. A user-defined tool gets one
    container and a set of PATHS; the identifiers are not available to it by any route. So the
    identifiers arrive as a file, produced by the IUC `collection_element_identifiers` tool, which
    usegalaxy.org installs.

    ⚠ **Feed it the SAME collection the pairs are about.** Nothing downstream can detect a mismatch:
    a self-pair list built from the wrong collection removes nothing, and a relabel map built from
    the wrong one renames nothing, both silently.
"""
    assert_no_nested_substitution(out)
    _stale = _check_orphans(out)
    if _stale:
        raise SystemExit(f"REFUSING: {len(_stale)} UDT(s) carry this generator's header but are no "
                         f"longer produced by build(): {_stale}. A renamed key leaves the old file "
                         f"behind, committed and checked by nothing. Delete it or restore its key.")
    return out



def sourmash_udt() -> str:
    """The one-job sourmash port: sketch every assembly, then compare, labelled by identifier."""
    indented = "\n".join(f"  {ln}" if ln else "" for ln in SOURMASH_GLUE.rstrip("\n").splitlines())
    return HEADER + f"""class: GalaxyUserTool
id: brc-sourmash-panel
version: "0.1.0"
name: sourmash sketch + compare over a panel (BRC UDT)
description: MinHash signatures for every assembly in a collection and the similarity matrix over them
container: quay.io/biocontainers/sourmash:4.9.4--hdfd78af_0
shell_command: |
  cat > rendered.txt <<'BRC_RENDERED'
  $(inputs.assemblies)
  BRC_RENDERED
  cat > sourmash_panel.py <<'BRC_PY'
{indented}
  BRC_PY
  python3 sourmash_panel.py --rendered rendered.txt --ids '$(inputs.identifiers.path)' --ksize '$(inputs.ksize)' --scaled '$(inputs.scaled)'
inputs:
  - name: assemblies
    type: data_collection
    collection_type: list
    label: assemblies to sketch
    help: The panel. One signature per element, sketched in collection order.
  - name: identifiers
    type: data
    format: txt
    label: element identifiers of THAT collection, one per line
    help: >-
      From the IUC "Extract element identifiers" tool, run on the same collection. A job cannot read
      a collection's identifiers, and sourmash's matrix labels are the strain names, so they are
      supplied here and paired by position -- with the count asserted before anything is sketched.
  - name: ksize
    type: integer
    value: 31
    label: k-mer size
  - name: scaled
    type: integer
    value: 1000
    min: 1
    label: MinHash scaled factor (lower = finer, more hashes)
    help: >-
      ⛔ EXPOSED BECAUSE THE TOOL'S OWN ERROR MESSAGE TELLS YOU TO CHANGE IT. A sequence too small
      to contribute a hash at this resolution sketches to nothing, and its row in the similarity
      matrix is then byte-identical to a genome that shares nothing with anyone -- so the tool
      refuses rather than publish it. That refusal is fatal for the WHOLE panel (one job sketches
      every assembly), and until this input existed the remedy it names was unreachable: `--scaled`
      was an argparse default the tool form neither declared nor passed. Measured at scaled=1000,
      k=31: a 360 nt viroid gives 1 hash, a 2 kb plasmid 3, a 5 kb virus 7, a 16.6 kb mitochondrion
      14, a 200 kb genome 195. Lower this for a panel with small members; the default suits
      megabase assemblies.
outputs:
  - name: similarity
    type: data
    format: csv
    from_work_dir: similarity.csv
    label: sourmash similarity matrix (CSV, labelled by strain)
  - name: heatmap
    type: data
    format: png
    from_work_dir: cmp.matrix.png
    label: sourmash clustered heatmap
  - name: dendrogram
    type: data
    format: png
    from_work_dir: cmp.dendro.png
    label: sourmash dendrogram
help:
  format: markdown
  content: |
    Both halves of the classic WF-A pair -- `sourmash_sketch` mapped over the panel and
    `sourmash_compare` over the resulting signatures -- in ONE job.

    ⚠ **That is not a shortcut, it is what the platform allows.** A user-defined tool cannot read a
    collection's element identifiers: measured on usegalaxy.org, `$(inputs.x)` renders File records
    whose `basename` is the DATASET name, with the identifiers nowhere in them. sourmash's matrix
    labels are the strain names, so the identifiers must be supplied alongside and paired by
    position — and pairing by position across two workflow steps would be a silent relabelling
    hazard. Sketching and comparing in one job keeps the pairing inside a single assertion.

    ⛔ **The assertion is the point.** If the identifier count and the assembly count disagree, the
    job REFUSES rather than sketching. A mismatched pair would produce a similarity matrix that is
    fully populated, plausible, and wrong about which strain each row is.

    The signature names are written by `sourmash sketch --name`, so the labels in the CSV come from
    the sketches themselves rather than from a post-hoc rename.
"""

def _check_orphans(rendered: dict[str, str]) -> list[str]:
    """UDT files on disk that carry THIS generator's header but no longer correspond to an output.

    ⛔ RENAMING A KEY LEAVES THE OLD FILE BEHIND, CHECKED BY NOTHING. `--check` iterates what
    build() PRODUCES, so a file it no longer produces is simply never visited; and the sibling
    generator's orphan sweep exempts anything whose header names a different generator -- which is
    exactly what these carry. A committed, registerable, referenced-by-nothing UDT was invisible to
    all three checkers. Enumerate the DISK and subtract.
    """
    udt_dir = ROOT / "udt"
    stale = []
    for f in sorted(udt_dir.glob("*.gxtool.yml")):
        if f.name in rendered:
            continue
        head = f.read_text(encoding="utf-8")[:400]
        if "build_inventory_udts.py" in head:
            stale.append(f.name)
    return stale


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare against udt/ and exit non-zero if any committed copy is stale")
    args = ap.parse_args()

    stale = []
    for filename, body in build().items():
        path = UDT / filename
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != body:
                stale.append(filename)
            continue
        path.write_text(body, encoding="utf-8")
        print(f"  {'unchanged' if current == body else 'wrote':>9} udt/{filename}")

    if args.check:
        for filename in stale:
            print(f"  STALE udt/{filename}")
        if stale:
            print("  Regenerate with: python3 scripts/build_inventory_udts.py")
            return 1
        print(f"  all committed inventory UDTs match their helpers ({len(build())} generated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
