#!/usr/bin/env python3
"""Verify that every provenance-stamped UDT in `udt/` still matches the wrapper it came from.

⚠ STANDARD LIBRARY ONLY, ON PURPOSE. The document in `udt/` is generated by a converter that needs
`galaxy-tool-source` (see the stamp), and this repository carries no dependency manifest -- its one
generator CI job installs `pyyaml` inline. Regenerating is a maintainer step; DETECTING STALENESS
must not be, so this re-hashes the wrapper with `hashlib` and compares. It answers "has the source
changed since this was generated?" and deliberately not "could I re-derive it?", which is the
question that would require the library.

    python3 scripts/check_udt_provenance.py          # non-zero if any stamped UDT is stale

⛔ AN UNSTAMPED FILE IS REPORTED, NOT SKIPPED SILENTLY. `udt/` also holds documents from
`build_softmask_udts.py`, which carries its own `--check`; those have no stamp and are listed by
name so that "0 stale" can never mean "0 examined".
"""

from __future__ import annotations

import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def stamp(path: pathlib.Path) -> dict[str, str]:
    """The `# provenance:` block a converted UDT carries in its header comment."""
    out: dict[str, str] = {}
    inside = False
    for line in path.read_text().splitlines():
        if line.startswith("# provenance:"):
            inside = True
            continue
        if inside:
            m = re.match(r"#\s{2,}(\w+):\s*(.*)$", line)
            if not m:
                break
            out[m.group(1)] = m.group(2).strip()
    return out


def sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def command_text(xml: pathlib.Path) -> str:
    """The <command> body, read the way the converter read it.

    ⚠ This is a TEXT slice, not a parse: the converter hashed `"".join(node.itertext())`, so the
    same bytes have to be recovered here without an XML library that expands anything. A regex is
    correct for exactly this because the hash only has to agree with the generator, and disagreeing
    is the alarm this script exists to raise.
    """
    m = re.search(r"<command[^>]*>(.*?)</command>", xml.read_text(), re.DOTALL)
    if not m:
        return ""
    body = m.group(1)
    body = body.replace("<![CDATA[", "").replace("]]>", "")
    return body


def main() -> int:
    stale, checked, unstamped = [], 0, []
    for udt in sorted((ROOT / "udt").glob("*.gxtool.yml")):
        prov = stamp(udt)
        if not prov.get("source"):
            unstamped.append(udt.name)
            continue
        checked += 1
        xml = ROOT / prov["source"]
        if not xml.exists():
            stale.append(f"{udt.name}: source {prov['source']} no longer exists")
            continue
        if sha(command_text(xml)) != prov.get("command_sha256"):
            stale.append(f"{udt.name}: <command> in {prov['source']} changed since generation")
        macros = xml.parent / "macros.xml"
        want = prov.get("macros_sha256", "")
        if want != "(no macros.xml)":
            # ⛔ THE MACROS FILE IS HASHED TOO, AND THAT IS THE WHOLE POINT OF STAMPING IT. 36 of
            # the 50 wrappers here declare their requirements ONLY through
            # <expand macro="requirements"/>, so a version bump that changes the container this UDT
            # pins happens in macros.xml and leaves the tool XML byte-identical.
            got = sha(macros.read_text()) if macros.exists() else "(no macros.xml)"
            if got != want:
                stale.append(f"{udt.name}: {xml.parent.name}/macros.xml changed since generation "
                             f"(this can change the pinned container: {prov.get('requirements')})")
    for line in stale:
        print(f"STALE  {line}")
    if unstamped:
        print(f"note: {len(unstamped)} UDT(s) carry no provenance stamp and were not checked here "
              f"(build_softmask_udts.py --check covers those): {', '.join(unstamped)}")
    print(f"{checked} stamped UDT(s) checked, {len(stale)} stale")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
